/* Generated by genstubs.pl
 (c) 2004 kangaroo
*/

#include <Cocoa/Cocoa.h>

#include <Foundation/NSObject.h>

void NSAutoreleasePool_addObject (NSAutoreleasePool* THIS, NSAutoreleasePool * anObject) {
	NSLog(@"NSAutoreleasePool_addObject");
	[THIS addObject:anObject];
}

NSAutoreleasePool * NSAutoreleasePool_alloc() {
	NSLog(@"NSAutoreleasePool_alloc()");
	return [NSAutoreleasePool alloc];
}
