/* Generated by genstubs.pl
 * (c) 2004 kangaroo, C.J. and Urs
 */

#include <Cocoa/Cocoa.h>

#include <Foundation/NSFormatter.h>

NSDateFormatter * NSDateFormatter_initWithDateFormat_allowNaturalLanguage (NSDateFormatter* THIS, NSString * format, BOOL flag) {
	NSLog(@"NSDateFormatter_initWithDateFormat_allowNaturalLanguage");
	return [THIS initWithDateFormat:format allowNaturalLanguage:flag];
}

NSString * NSDateFormatter_dateFormat (NSDateFormatter* THIS) {
	NSLog(@"NSDateFormatter_dateFormat");
	return [THIS dateFormat];
}

BOOL NSDateFormatter_allowsNaturalLanguage (NSDateFormatter* THIS) {
	NSLog(@"NSDateFormatter_allowsNaturalLanguage");
	return [THIS allowsNaturalLanguage];
}

NSDateFormatter * NSDateFormatter_alloc(){
	NSLog(@"NSDateFormatter_alloc()");
	return [ NSDateFormatter alloc ];
}