/* Generated by genstubs.pl
 * (c) 2004 kangaroo, C.J. and Urs
 */

#include <Cocoa/Cocoa.h>

#include <Foundation/NSObject.h>
#include <Foundation/NSAutoreleasePool.h>
#include <Foundation/NSDate.h>
#include <Foundation/NSPort.h>

void NSDebug$_enableRelease (BOOL enable) {
	NSLog(@"NSDebug$_enableRelease");
	[NSDebug enableRelease:enable];
}

void NSDebug$_showPools () {
	NSLog(@"NSDebug$_showPools");
	[NSDebug showPools];
}

void NSDebug$_resetTotalAutoreleasedObjects () {
	NSLog(@"NSDebug$_resetTotalAutoreleasedObjects");
	[NSDebug resetTotalAutoreleasedObjects];
}

unsigned NSDebug$_totalAutoreleasedObjects () {
	NSLog(@"NSDebug$_totalAutoreleasedObjects");
	return [NSDebug totalAutoreleasedObjects];
}

void NSDebug$_enableFreedObjectCheck (BOOL enable) {
	NSLog(@"NSDebug$_enableFreedObjectCheck");
	[NSDebug enableFreedObjectCheck:enable];
}

unsigned int NSDebug$_autoreleasedObjectCount () {
	NSLog(@"NSDebug$_autoreleasedObjectCount");
	return [NSDebug autoreleasedObjectCount];
}

unsigned int NSDebug$_topAutoreleasePoolCount () {
	NSLog(@"NSDebug$_topAutoreleasePoolCount");
	return [NSDebug topAutoreleasePoolCount];
}

unsigned int NSDebug$_poolCountHighWaterMark () {
	NSLog(@"NSDebug$_poolCountHighWaterMark");
	return [NSDebug poolCountHighWaterMark];
}

void NSDebug$_setPoolCountHighWaterMark (unsigned int count) {
	NSLog(@"NSDebug$_setPoolCountHighWaterMark");
	[NSDebug setPoolCountHighWaterMark:count];
}

unsigned int NSDebug$_poolCountHighWaterResolution () {
	NSLog(@"NSDebug$_poolCountHighWaterResolution");
	return [NSDebug poolCountHighWaterResolution];
}

void NSDebug$_setPoolCountHighWaterResolution (unsigned int res) {
	NSLog(@"NSDebug$_setPoolCountHighWaterResolution");
	[NSDebug setPoolCountHighWaterResolution:res];
}

NSDebug * NSDebug_alloc(){
	NSLog(@"NSDebug_alloc()");
	return [ NSDebug alloc ];
}