/* Generated by genstubs.pl
 * (c) 2004 kangaroo, C.J. and Urs
 */

#include <Cocoa/Cocoa.h>

#include <Foundation/NSObjCRuntime.h>

NSDecimal * NSDecimal_alloc(){
	NSLog(@"NSDecimal_alloc()");
	return [ NSDecimal alloc ];
}