/* Generated by genstubs.pl
 * (c) 2004 kangaroo, C.J. and Urs
 */

#include <Cocoa/Cocoa.h>

#include <Foundation/NSProxy.h>

NSDistantObject * NSDistantObject$_proxyWithTarget_connection (id target, NSConnection * connection) {
	NSLog(@"NSDistantObject$_proxyWithTarget_connection");
	return [NSDistantObject proxyWithTarget:target connection:connection];
}

NSDistantObject * NSDistantObject_initWithTarget_connection (NSDistantObject* THIS, id target, NSConnection * connection) {
	NSLog(@"NSDistantObject_initWithTarget_connection");
	return [THIS initWithTarget:target connection:connection];
}

NSDistantObject * NSDistantObject$_proxyWithLocal_connection (id target, NSConnection * connection) {
	NSLog(@"NSDistantObject$_proxyWithLocal_connection");
	return [NSDistantObject proxyWithLocal:target connection:connection];
}

NSDistantObject * NSDistantObject_initWithLocal_connection (NSDistantObject* THIS, id target, NSConnection * connection) {
	NSLog(@"NSDistantObject_initWithLocal_connection");
	return [THIS initWithLocal:target connection:connection];
}

void NSDistantObject_setProtocolForProxy (NSDistantObject* THIS, Protocol * proto) {
	NSLog(@"NSDistantObject_setProtocolForProxy");
	[THIS setProtocolForProxy:proto];
}

NSConnection * NSDistantObject_connectionForProxy (NSDistantObject* THIS) {
	NSLog(@"NSDistantObject_connectionForProxy");
	return [THIS connectionForProxy];
}

NSDistantObject * NSDistantObject_alloc(){
	NSLog(@"NSDistantObject_alloc()");
	return [ NSDistantObject alloc ];
}