/* Generated by genstubs.pl
 (c) 2004 kangaroo
*/

#include <Cocoa/Cocoa.h>

#include <Foundation/NSObject.h>

#include <stdarg.h>

#include <setjmp.h>

NSException * NSException_exceptionWithName_reason_userInfo (NSException* THIS, NSString * name, NSString * reason, NSDictionary * userInfo) {
	NSLog(@"NSException_exceptionWithName_reason_userInfo");
	return [THIS exceptionWithName:name reason:reason userInfo:userInfo];
}

NSException * NSException_initWithName_reason_userInfo (NSException* THIS, NSString * aName, NSString * aReason, NSDictionary * aUserInfo) {
	NSLog(@"NSException_initWithName_reason_userInfo");
	return [THIS initWithName:aName reason:aReason userInfo:aUserInfo];
}

NSString * NSException_name (NSException* THIS) {
	NSLog(@"NSException_name");
	return [THIS name];
}
NSString * NSException_reason (NSException* THIS) {
	NSLog(@"NSException_reason");
	return [THIS reason];
}
NSDictionary * NSException_userInfo (NSException* THIS) {
	NSLog(@"NSException_userInfo");
	return [THIS userInfo];
}
void NSException_raise (NSException* THIS) {
	NSLog(@"NSException_raise");
	[THIS raise];
}
/* UNSUPPORTED: 
+ (void)raise:(NSString *)name format:(NSString *)format, ...;
 */

void NSException_raise_format_arguments (NSException* THIS, NSString * name, NSString * format, va_list argList) {
	NSLog(@"NSException_raise_format_arguments");
	[THIS raise:name format:format arguments:argList];
}

NSAssertionHandler * NSException_currentHandler (NSException* THIS) {
	NSLog(@"NSException_currentHandler");
	return [THIS currentHandler];
}
/* UNSUPPORTED: 
- (void)handleFailureInMethod:(SEL)selector object:(id)object file:(NSString *)fileName lineNumber:(int)line description:(NSString *)format,...;
 */

/* UNSUPPORTED: 
- (void)handleFailureInFunction:(NSString *)functionName file:(NSString *)fileName lineNumber:(int)line description:(NSString *)format,...;
 */

NSException * NSException_alloc() {
	NSLog(@"NSException_alloc()");
	return [NSException alloc];
}
