/* Generated by genstubs.pl
 (c) 2004 kangaroo
*/

#include <Cocoa/Cocoa.h>

#include <Foundation/NSObject.h>

#include <Foundation/NSRange.h>

NSString * NSFormatter_stringForObjectValue (NSFormatter* THIS, NSFormatter * obj) {
	NSLog(@"NSFormatter_stringForObjectValue");
	return [THIS stringForObjectValue:obj];
}

NSAttributedString * NSFormatter_attributedStringForObjectValue_withDefaultAttributes (NSFormatter* THIS, NSFormatter * obj, NSDictionary * attrs) {
	NSLog(@"NSFormatter_attributedStringForObjectValue_withDefaultAttributes");
	return [THIS attributedStringForObjectValue:obj withDefaultAttributes:attrs];
}

NSString * NSFormatter_editingStringForObjectValue (NSFormatter* THIS, NSFormatter * obj) {
	NSLog(@"NSFormatter_editingStringForObjectValue");
	return [THIS editingStringForObjectValue:obj];
}

BOOL NSFormatter_getObjectValue_forString_errorDescription (NSFormatter* THIS, NSFormatter * * obj, NSString * string, NSString ** error) {
	NSLog(@"NSFormatter_getObjectValue_forString_errorDescription");
	return [THIS getObjectValue:obj forString:string errorDescription:error];
}

BOOL NSFormatter_isPartialStringValid_newEditingString_errorDescription (NSFormatter* THIS, NSString * partialString, NSString ** newString, NSString ** error) {
	NSLog(@"NSFormatter_isPartialStringValid_newEditingString_errorDescription");
	return [THIS isPartialStringValid:partialString newEditingString:newString errorDescription:error];
}

BOOL NSFormatter_isPartialStringValid_proposedSelectedRange_originalString_originalSelectedRange_errorDescription (NSFormatter* THIS, NSString ** partialStringPtr, NSRangePointer proposedSelRangePtr, NSString * origString, NSRange origSelRange, NSString ** error) {
	NSLog(@"NSFormatter_isPartialStringValid_proposedSelectedRange_originalString_originalSelectedRange_errorDescription");
	return [THIS isPartialStringValid:partialStringPtr proposedSelectedRange:proposedSelRangePtr originalString:origString originalSelectedRange:origSelRange errorDescription:error];
}

NSFormatter * NSFormatter_alloc() {
	NSLog(@"NSFormatter_alloc()");
	return [NSFormatter alloc];
}
