/* Generated by genstubs.pl
 (c) 2004 kangaroo
*/

#include <Cocoa/Cocoa.h>

#include <AvailabilityMacros.h>

#include <Foundation/NSObject.h>

NSHTTPCookieStorage * NSHTTPCookieStorage_sharedHTTPCookieStorage (NSHTTPCookieStorage* THIS) {
	NSLog(@"NSHTTPCookieStorage_sharedHTTPCookieStorage");
	return [THIS sharedHTTPCookieStorage];
}
NSArray * NSHTTPCookieStorage_cookies (NSHTTPCookieStorage* THIS) {
	NSLog(@"NSHTTPCookieStorage_cookies");
	return [THIS cookies];
}
void NSHTTPCookieStorage_setCookie (NSHTTPCookieStorage* THIS, NSHTTPCookie * cookie) {
	NSLog(@"NSHTTPCookieStorage_setCookie");
	[THIS setCookie:cookie];
}

void NSHTTPCookieStorage_deleteCookie (NSHTTPCookieStorage* THIS, NSHTTPCookie * cookie) {
	NSLog(@"NSHTTPCookieStorage_deleteCookie");
	[THIS deleteCookie:cookie];
}

NSArray * NSHTTPCookieStorage_cookiesForURL (NSHTTPCookieStorage* THIS, NSURL * URL) {
	NSLog(@"NSHTTPCookieStorage_cookiesForURL");
	return [THIS cookiesForURL:URL];
}

void NSHTTPCookieStorage_setCookies_forURL_mainDocumentURL (NSHTTPCookieStorage* THIS, NSArray * cookies, NSURL * URL, NSURL * mainDocumentURL) {
	NSLog(@"NSHTTPCookieStorage_setCookies_forURL_mainDocumentURL");
	[THIS setCookies:cookies forURL:URL mainDocumentURL:mainDocumentURL];
}

NSHTTPCookieAcceptPolicy NSHTTPCookieStorage_cookieAcceptPolicy (NSHTTPCookieStorage* THIS) {
	NSLog(@"NSHTTPCookieStorage_cookieAcceptPolicy");
	return [THIS cookieAcceptPolicy];
}
void NSHTTPCookieStorage_setCookieAcceptPolicy (NSHTTPCookieStorage* THIS, NSHTTPCookieAcceptPolicy cookieAcceptPolicy) {
	NSLog(@"NSHTTPCookieStorage_setCookieAcceptPolicy");
	[THIS setCookieAcceptPolicy:cookieAcceptPolicy];
}

NSHTTPCookieStorage * NSHTTPCookieStorage_alloc() {
	NSLog(@"NSHTTPCookieStorage_alloc()");
	return [NSHTTPCookieStorage alloc];
}
