/* Generated by genstubs.pl
 * (c) 2004 kangaroo, C.J. and Urs
 */

#include <Cocoa/Cocoa.h>

#include <Foundation/NSObject.h>

NSJavaSetup * NSJavaSetup_alloc(){
	NSLog(@"NSJavaSetup_alloc()");
	return [ NSJavaSetup alloc ];
}