/* Generated by genstubs.pl
 * (c) 2004 kangaroo, C.J. and Urs
 */

#include <Cocoa/Cocoa.h>

#include <Foundation/NSObject.h>

NSString * NSNotification_name (NSNotification* THIS) {
	NSLog(@"NSNotification_name");
	return [THIS name];
}

NSNotification * NSNotification_object (NSNotification* THIS) {
	NSLog(@"NSNotification_object");
	return [THIS object];
}

NSDictionary * NSNotification_userInfo (NSNotification* THIS) {
	NSLog(@"NSNotification_userInfo");
	return [THIS userInfo];
}

NSNotification * NSNotification$_notificationWithName_object (NSString * aName, id anObject) {
	NSLog(@"NSNotification$_notificationWithName_object");
	return [NSNotification notificationWithName:aName object:anObject];
}

NSNotification * NSNotification$_notificationWithName_object_userInfo (NSString * aName, id anObject, NSDictionary * aUserInfo) {
	NSLog(@"NSNotification$_notificationWithName_object_userInfo");
	return [NSNotification notificationWithName:aName object:anObject userInfo:aUserInfo];
}

NSNotification * NSNotification$_defaultCenter () {
	NSLog(@"NSNotification$_defaultCenter");
	return [NSNotification defaultCenter];
}

void NSNotification_addObserver_selector_name_object (NSNotification* THIS, id observer, SEL aSelector, NSString * aName, id anObject) {
	NSLog(@"NSNotification_addObserver_selector_name_object");
	[THIS addObserver:observer selector:aSelector name:aName object:anObject];
}

void NSNotification_postNotification (NSNotification* THIS, NSNotification * notification) {
	NSLog(@"NSNotification_postNotification");
	[THIS postNotification:notification];
}

void NSNotification_postNotificationName_object (NSNotification* THIS, NSString * aName, id anObject) {
	NSLog(@"NSNotification_postNotificationName_object");
	[THIS postNotificationName:aName object:anObject];
}

void NSNotification_postNotificationName_object_userInfo (NSNotification* THIS, NSString * aName, id anObject, NSDictionary * aUserInfo) {
	NSLog(@"NSNotification_postNotificationName_object_userInfo");
	[THIS postNotificationName:aName object:anObject userInfo:aUserInfo];
}

void NSNotification_removeObserver (NSNotification* THIS, id observer) {
	NSLog(@"NSNotification_removeObserver");
	[THIS removeObserver:observer];
}

void NSNotification_removeObserver_name_object (NSNotification* THIS, id observer, NSString * aName, id anObject) {
	NSLog(@"NSNotification_removeObserver_name_object");
	[THIS removeObserver:observer name:aName object:anObject];
}

NSNotification * NSNotification_alloc(){
	NSLog(@"NSNotification_alloc()");
	return [ NSNotification alloc ];
}