/* Generated by genstubs.pl
 * (c) 2004 kangaroo, C.J. and Urs
 */

#include <Cocoa/Cocoa.h>

#include <Foundation/NSObject.h>

NSNotificationQueue * NSNotificationQueue$_defaultQueue () {
	NSLog(@"NSNotificationQueue$_defaultQueue");
	return [NSNotificationQueue defaultQueue];
}

NSNotificationQueue * NSNotificationQueue_initWithNotificationCenter (NSNotificationQueue* THIS, NSNotificationCenter * notificationCenter) {
	NSLog(@"NSNotificationQueue_initWithNotificationCenter");
	return [THIS initWithNotificationCenter:notificationCenter];
}

void NSNotificationQueue_enqueueNotification_postingStyle (NSNotificationQueue* THIS, NSNotification * notification, NSPostingStyle postingStyle) {
	NSLog(@"NSNotificationQueue_enqueueNotification_postingStyle");
	[THIS enqueueNotification:notification postingStyle:postingStyle];
}

void NSNotificationQueue_enqueueNotification_postingStyle_coalesceMask_forModes (NSNotificationQueue* THIS, NSNotification * notification, NSPostingStyle postingStyle, unsigned coalesceMask, NSArray * modes) {
	NSLog(@"NSNotificationQueue_enqueueNotification_postingStyle_coalesceMask_forModes");
	[THIS enqueueNotification:notification postingStyle:postingStyle coalesceMask:coalesceMask forModes:modes];
}

void NSNotificationQueue_dequeueNotificationsMatching_coalesceMask (NSNotificationQueue* THIS, NSNotification * notification, unsigned coalesceMask) {
	NSLog(@"NSNotificationQueue_dequeueNotificationsMatching_coalesceMask");
	[THIS dequeueNotificationsMatching:notification coalesceMask:coalesceMask];
}

NSNotificationQueue * NSNotificationQueue_alloc(){
	NSLog(@"NSNotificationQueue_alloc()");
	return [ NSNotificationQueue alloc ];
}