/* Generated by genstubs.pl
 * (c) 2004 kangaroo, C.J. and Urs
 */

#include <Cocoa/Cocoa.h>

#include <Foundation/NSObject.h>

NSNull * NSNull$_null () {
	NSLog(@"NSNull$_null");
	return [NSNull null];
}

NSNull * NSNull_alloc(){
	NSLog(@"NSNull_alloc()");
	return [ NSNull alloc ];
}