/* Generated by genstubs.pl
 * (c) 2004 kangaroo, C.J. and Urs
 */

#include <Cocoa/Cocoa.h>

#include <objc/objc.h>

NSObjCRuntime * NSObjCRuntime_alloc(){
	NSLog(@"NSObjCRuntime_alloc()");
	return [ NSObjCRuntime alloc ];
}