/* Generated by genstubs.pl
 * (c) 2004 kangaroo, C.J. and Urs
 */

#include <Cocoa/Cocoa.h>

#include <Foundation/NSObject.h>

NSProxy * NSProxy$_alloc () {
	NSLog(@"NSProxy$_alloc");
	return [NSProxy alloc];
}

NSProxy * NSProxy$_allocWithZone (NSZone * zone) {
	NSLog(@"NSProxy$_allocWithZone");
	return [NSProxy allocWithZone:zone];
}

Class NSProxy$_class () {
	NSLog(@"NSProxy$_class");
	return [NSProxy class];
}

void NSProxy_forwardInvocation (NSProxy* THIS, NSInvocation * invocation) {
	NSLog(@"NSProxy_forwardInvocation");
	[THIS forwardInvocation:invocation];
}

NSMethodSignature * NSProxy_methodSignatureForSelector (NSProxy* THIS, SEL sel) {
	NSLog(@"NSProxy_methodSignatureForSelector");
	return [THIS methodSignatureForSelector:sel];
}

void NSProxy_dealloc (NSProxy* THIS) {
	NSLog(@"NSProxy_dealloc");
	[THIS dealloc];
}

NSString * NSProxy_description (NSProxy* THIS) {
	NSLog(@"NSProxy_description");
	return [THIS description];
}

BOOL NSProxy$_respondsToSelector (SEL aSelector) {
	NSLog(@"NSProxy$_respondsToSelector");
	return [NSProxy respondsToSelector:aSelector];
}

NSProxy * NSProxy_alloc(){
	NSLog(@"NSProxy_alloc()");
	return [ NSProxy alloc ];
}