/* Generated by genstubs.pl
 * (c) 2004 kangaroo, C.J. and Urs
 */

#include <Cocoa/Cocoa.h>

#include <Foundation/NSValue.h>

NSValue * NSRange$_valueWithRange (NSRange range) {
	NSLog(@"NSRange$_valueWithRange");
	return [NSRange valueWithRange:range];
}

NSRange NSRange_rangeValue (NSRange* THIS) {
	NSLog(@"NSRange_rangeValue");
	return [THIS rangeValue];
}

NSRange * NSRange_alloc(){
	NSLog(@"NSRange_alloc()");
	return [ NSRange alloc ];
}