/* Generated by genstubs.pl
 (c) 2004 kangaroo
*/

#include <Cocoa/Cocoa.h>

#include <Foundation/NSValue.h>

NSValue * NSRange_valueWithRange (NSRange* THIS, NSRange range) {
	NSLog(@"NSRange_valueWithRange");
	return [THIS valueWithRange:range];
}

NSRange NSRange_rangeValue (NSRange* THIS) {
	NSLog(@"NSRange_rangeValue");
	return [THIS rangeValue];
}
NSRange * NSRange_alloc() {
	NSLog(@"NSRange_alloc()");
	return [NSRange alloc];
}
