/* Generated by genstubs.pl
 * (c) 2004 kangaroo, C.J. and Urs
 */

#include <Cocoa/Cocoa.h>

#include <Foundation/NSObject.h>

NSScriptKeyValueCoding * NSScriptKeyValueCoding_valueAtIndex_inPropertyWithKey (NSScriptKeyValueCoding* THIS, unsigned index, NSString * key) {
	NSLog(@"NSScriptKeyValueCoding_valueAtIndex_inPropertyWithKey");
	return [THIS valueAtIndex:index inPropertyWithKey:key];
}

NSScriptKeyValueCoding * NSScriptKeyValueCoding_valueWithName_inPropertyWithKey (NSScriptKeyValueCoding* THIS, NSString * name, NSString * key) {
	NSLog(@"NSScriptKeyValueCoding_valueWithName_inPropertyWithKey");
	return [THIS valueWithName:name inPropertyWithKey:key];
}

NSScriptKeyValueCoding * NSScriptKeyValueCoding_valueWithUniqueID_inPropertyWithKey (NSScriptKeyValueCoding* THIS, id uniqueID, NSString * key) {
	NSLog(@"NSScriptKeyValueCoding_valueWithUniqueID_inPropertyWithKey");
	return [THIS valueWithUniqueID:uniqueID inPropertyWithKey:key];
}

void NSScriptKeyValueCoding_replaceValueAtIndex_inPropertyWithKey_withValue (NSScriptKeyValueCoding* THIS, unsigned index, NSString * key, id value) {
	NSLog(@"NSScriptKeyValueCoding_replaceValueAtIndex_inPropertyWithKey_withValue");
	[THIS replaceValueAtIndex:index inPropertyWithKey:key withValue:value];
}

void NSScriptKeyValueCoding_insertValue_atIndex_inPropertyWithKey (NSScriptKeyValueCoding* THIS, id value, unsigned index, NSString * key) {
	NSLog(@"NSScriptKeyValueCoding_insertValue_atIndex_inPropertyWithKey");
	[THIS insertValue:value atIndex:index inPropertyWithKey:key];
}

void NSScriptKeyValueCoding_removeValueAtIndex_fromPropertyWithKey (NSScriptKeyValueCoding* THIS, unsigned index, NSString * key) {
	NSLog(@"NSScriptKeyValueCoding_removeValueAtIndex_fromPropertyWithKey");
	[THIS removeValueAtIndex:index fromPropertyWithKey:key];
}

void NSScriptKeyValueCoding_insertValue_inPropertyWithKey (NSScriptKeyValueCoding* THIS, id value, NSString * key) {
	NSLog(@"NSScriptKeyValueCoding_insertValue_inPropertyWithKey");
	[THIS insertValue:value inPropertyWithKey:key];
}

NSScriptKeyValueCoding * NSScriptKeyValueCoding_coerceValue_forKey (NSScriptKeyValueCoding* THIS, id value, NSString * key) {
	NSLog(@"NSScriptKeyValueCoding_coerceValue_forKey");
	return [THIS coerceValue:value forKey:key];
}

NSScriptKeyValueCoding * NSScriptKeyValueCoding_alloc(){
	NSLog(@"NSScriptKeyValueCoding_alloc()");
	return [ NSScriptKeyValueCoding alloc ];
}