/* Generated by genstubs.pl
 (c) 2004 kangaroo
*/

#include <Cocoa/Cocoa.h>

#include <Foundation/NSClassDescription.h>

NSScriptClassDescription * NSScriptClassDescription_initWithSuiteName_className_dictionary (NSScriptClassDescription* THIS, NSString * suiteName, NSString * className, NSDictionary * dict) {
	NSLog(@"NSScriptClassDescription_initWithSuiteName_className_dictionary");
	return [THIS initWithSuiteName:suiteName className:className dictionary:dict];
}

NSString * NSScriptClassDescription_suiteName (NSScriptClassDescription* THIS) {
	NSLog(@"NSScriptClassDescription_suiteName");
	return [THIS suiteName];
}
NSString * NSScriptClassDescription_className (NSScriptClassDescription* THIS) {
	NSLog(@"NSScriptClassDescription_className");
	return [THIS className];
}
NSScriptClassDescription * NSScriptClassDescription_superclassDescription (NSScriptClassDescription* THIS) {
	NSLog(@"NSScriptClassDescription_superclassDescription");
	return [THIS superclassDescription];
}
unsigned long NSScriptClassDescription_appleEventCode (NSScriptClassDescription* THIS) {
	NSLog(@"NSScriptClassDescription_appleEventCode");
	return [THIS appleEventCode];
}
BOOL NSScriptClassDescription_matchesAppleEventCode (NSScriptClassDescription* THIS, unsigned long code) {
	NSLog(@"NSScriptClassDescription_matchesAppleEventCode");
	return [THIS matchesAppleEventCode:code];
}

BOOL NSScriptClassDescription_supportsCommand (NSScriptClassDescription* THIS, NSScriptCommandDescription * commandDef) {
	NSLog(@"NSScriptClassDescription_supportsCommand");
	return [THIS supportsCommand:commandDef];
}

SEL NSScriptClassDescription_selectorForCommand (NSScriptClassDescription* THIS, NSScriptCommandDescription * commandDef) {
	NSLog(@"NSScriptClassDescription_selectorForCommand");
	return [THIS selectorForCommand:commandDef];
}

NSString * NSScriptClassDescription_typeForKey (NSScriptClassDescription* THIS, NSString * key) {
	NSLog(@"NSScriptClassDescription_typeForKey");
	return [THIS typeForKey:key];
}

NSScriptClassDescription * NSScriptClassDescription_classDescriptionForKey (NSScriptClassDescription* THIS, NSString * key) {
	NSLog(@"NSScriptClassDescription_classDescriptionForKey");
	return [THIS classDescriptionForKey:key];
}

unsigned long NSScriptClassDescription_appleEventCodeForKey (NSScriptClassDescription* THIS, NSString * key) {
	NSLog(@"NSScriptClassDescription_appleEventCodeForKey");
	return [THIS appleEventCodeForKey:key];
}

BOOL NSScriptClassDescription_isReadOnlyKey (NSScriptClassDescription* THIS, NSString * key) {
	NSLog(@"NSScriptClassDescription_isReadOnlyKey");
	return [THIS isReadOnlyKey:key];
}

NSString * NSScriptClassDescription_keyWithAppleEventCode (NSScriptClassDescription* THIS, unsigned long code) {
	NSLog(@"NSScriptClassDescription_keyWithAppleEventCode");
	return [THIS keyWithAppleEventCode:code];
}

NSString * NSScriptClassDescription_defaultSubcontainerAttributeKey (NSScriptClassDescription* THIS) {
	NSLog(@"NSScriptClassDescription_defaultSubcontainerAttributeKey");
	return [THIS defaultSubcontainerAttributeKey];
}
BOOL NSScriptClassDescription_isLocationRequiredToCreateForKey (NSScriptClassDescription* THIS, NSString * toManyRelationshipKey) {
	NSLog(@"NSScriptClassDescription_isLocationRequiredToCreateForKey");
	return [THIS isLocationRequiredToCreateForKey:toManyRelationshipKey];
}

NSString * NSScriptClassDescription_className (NSScriptClassDescription* THIS) {
	NSLog(@"NSScriptClassDescription_className");
	return [THIS className];
}
unsigned long NSScriptClassDescription_classCode (NSScriptClassDescription* THIS) {
	NSLog(@"NSScriptClassDescription_classCode");
	return [THIS classCode];
}
NSScriptClassDescription * NSScriptClassDescription_alloc() {
	NSLog(@"NSScriptClassDescription_alloc()");
	return [NSScriptClassDescription alloc];
}
