/* Generated by genstubs.pl
 * (c) 2004 kangaroo, C.J. and Urs
 */

#include <Cocoa/Cocoa.h>

#include <Foundation/NSObject.h>

NSScriptSuiteRegistry * NSScriptSuiteRegistry$_sharedScriptSuiteRegistry () {
	NSLog(@"NSScriptSuiteRegistry$_sharedScriptSuiteRegistry");
	return [NSScriptSuiteRegistry sharedScriptSuiteRegistry];
}

void NSScriptSuiteRegistry$_setSharedScriptSuiteRegistry (NSScriptSuiteRegistry * registry) {
	NSLog(@"NSScriptSuiteRegistry$_setSharedScriptSuiteRegistry");
	[NSScriptSuiteRegistry setSharedScriptSuiteRegistry:registry];
}

NSArray * NSScriptSuiteRegistry_suiteNames (NSScriptSuiteRegistry* THIS) {
	NSLog(@"NSScriptSuiteRegistry_suiteNames");
	return [THIS suiteNames];
}

NSDictionary * NSScriptSuiteRegistry_commandDescriptionsInSuite (NSScriptSuiteRegistry* THIS, NSString * suiteName) {
	NSLog(@"NSScriptSuiteRegistry_commandDescriptionsInSuite");
	return [THIS commandDescriptionsInSuite:suiteName];
}

NSDictionary * NSScriptSuiteRegistry_classDescriptionsInSuite (NSScriptSuiteRegistry* THIS, NSString * suiteName) {
	NSLog(@"NSScriptSuiteRegistry_classDescriptionsInSuite");
	return [THIS classDescriptionsInSuite:suiteName];
}

unsigned long NSScriptSuiteRegistry_appleEventCodeForSuite (NSScriptSuiteRegistry* THIS, NSString * suiteName) {
	NSLog(@"NSScriptSuiteRegistry_appleEventCodeForSuite");
	return [THIS appleEventCodeForSuite:suiteName];
}

NSString * NSScriptSuiteRegistry_suiteForAppleEventCode (NSScriptSuiteRegistry* THIS, unsigned long code) {
	NSLog(@"NSScriptSuiteRegistry_suiteForAppleEventCode");
	return [THIS suiteForAppleEventCode:code];
}

NSBundle * NSScriptSuiteRegistry_bundleForSuite (NSScriptSuiteRegistry* THIS, NSString * suiteName) {
	NSLog(@"NSScriptSuiteRegistry_bundleForSuite");
	return [THIS bundleForSuite:suiteName];
}

NSScriptCommandDescription * NSScriptSuiteRegistry_commandDescriptionWithAppleEventClass_andAppleEventCode (NSScriptSuiteRegistry* THIS, unsigned long eventClass, unsigned long commandCode) {
	NSLog(@"NSScriptSuiteRegistry_commandDescriptionWithAppleEventClass_andAppleEventCode");
	return [THIS commandDescriptionWithAppleEventClass:eventClass andAppleEventCode:commandCode];
}

NSScriptClassDescription * NSScriptSuiteRegistry_classDescriptionWithAppleEventCode (NSScriptSuiteRegistry* THIS, unsigned long classCode) {
	NSLog(@"NSScriptSuiteRegistry_classDescriptionWithAppleEventCode");
	return [THIS classDescriptionWithAppleEventCode:classCode];
}

void NSScriptSuiteRegistry_registerCommandDescription (NSScriptSuiteRegistry* THIS, NSScriptCommandDescription * commandDef) {
	NSLog(@"NSScriptSuiteRegistry_registerCommandDescription");
	[THIS registerCommandDescription:commandDef];
}

void NSScriptSuiteRegistry_registerClassDescription (NSScriptSuiteRegistry* THIS, NSScriptClassDescription * classDesc) {
	NSLog(@"NSScriptSuiteRegistry_registerClassDescription");
	[THIS registerClassDescription:classDesc];
}

void NSScriptSuiteRegistry_loadSuitesFromBundle (NSScriptSuiteRegistry* THIS, NSBundle * bundle) {
	NSLog(@"NSScriptSuiteRegistry_loadSuitesFromBundle");
	[THIS loadSuitesFromBundle:bundle];
}

void NSScriptSuiteRegistry_loadSuiteWithDictionary_fromBundle (NSScriptSuiteRegistry* THIS, NSDictionary * dict, NSBundle * bundle) {
	NSLog(@"NSScriptSuiteRegistry_loadSuiteWithDictionary_fromBundle");
	[THIS loadSuiteWithDictionary:dict fromBundle:bundle];
}

NSData * NSScriptSuiteRegistry_aeteResource (NSScriptSuiteRegistry* THIS, NSString * languageName) {
	NSLog(@"NSScriptSuiteRegistry_aeteResource");
	return [THIS aeteResource:languageName];
}

NSScriptSuiteRegistry * NSScriptSuiteRegistry_alloc(){
	NSLog(@"NSScriptSuiteRegistry_alloc()");
	return [ NSScriptSuiteRegistry alloc ];
}