/* Generated by genstubs.pl
 (c) 2004 kangaroo
*/

#include <Cocoa/Cocoa.h>

#include <Foundation/NSObject.h>

NSTask * NSTask_init (NSTask* THIS) {
	NSLog(@"NSTask_init");
	return [THIS init];
}
void NSTask_setLaunchPath (NSTask* THIS, NSString * path) {
	NSLog(@"NSTask_setLaunchPath");
	[THIS setLaunchPath:path];
}

void NSTask_setArguments (NSTask* THIS, NSArray * arguments) {
	NSLog(@"NSTask_setArguments");
	[THIS setArguments:arguments];
}

void NSTask_setEnvironment (NSTask* THIS, NSDictionary * dict) {
	NSLog(@"NSTask_setEnvironment");
	[THIS setEnvironment:dict];
}

void NSTask_setCurrentDirectoryPath (NSTask* THIS, NSString * path) {
	NSLog(@"NSTask_setCurrentDirectoryPath");
	[THIS setCurrentDirectoryPath:path];
}

void NSTask_setStandardInput (NSTask* THIS, NSTask * input) {
	NSLog(@"NSTask_setStandardInput");
	[THIS setStandardInput:input];
}

void NSTask_setStandardOutput (NSTask* THIS, NSTask * output) {
	NSLog(@"NSTask_setStandardOutput");
	[THIS setStandardOutput:output];
}

void NSTask_setStandardError (NSTask* THIS, NSTask * error) {
	NSLog(@"NSTask_setStandardError");
	[THIS setStandardError:error];
}

NSString * NSTask_launchPath (NSTask* THIS) {
	NSLog(@"NSTask_launchPath");
	return [THIS launchPath];
}
NSArray * NSTask_arguments (NSTask* THIS) {
	NSLog(@"NSTask_arguments");
	return [THIS arguments];
}
NSDictionary * NSTask_environment (NSTask* THIS) {
	NSLog(@"NSTask_environment");
	return [THIS environment];
}
NSString * NSTask_currentDirectoryPath (NSTask* THIS) {
	NSLog(@"NSTask_currentDirectoryPath");
	return [THIS currentDirectoryPath];
}
NSTask * NSTask_standardInput (NSTask* THIS) {
	NSLog(@"NSTask_standardInput");
	return [THIS standardInput];
}
NSTask * NSTask_standardOutput (NSTask* THIS) {
	NSLog(@"NSTask_standardOutput");
	return [THIS standardOutput];
}
NSTask * NSTask_standardError (NSTask* THIS) {
	NSLog(@"NSTask_standardError");
	return [THIS standardError];
}
void NSTask_launch (NSTask* THIS) {
	NSLog(@"NSTask_launch");
	[THIS launch];
}
void NSTask_interrupt (NSTask* THIS) {
	NSLog(@"NSTask_interrupt");
	[THIS interrupt];
}
void NSTask_terminate (NSTask* THIS) {
	NSLog(@"NSTask_terminate");
	[THIS terminate];
}
BOOL NSTask_suspend (NSTask* THIS) {
	NSLog(@"NSTask_suspend");
	return [THIS suspend];
}
BOOL NSTask_resume (NSTask* THIS) {
	NSLog(@"NSTask_resume");
	return [THIS resume];
}
int NSTask_processIdentifier (NSTask* THIS) {
	NSLog(@"NSTask_processIdentifier");
	return [THIS processIdentifier];
}
BOOL NSTask_isRunning (NSTask* THIS) {
	NSLog(@"NSTask_isRunning");
	return [THIS isRunning];
}
int NSTask_terminationStatus (NSTask* THIS) {
	NSLog(@"NSTask_terminationStatus");
	return [THIS terminationStatus];
}
NSTask * NSTask_launchedTaskWithLaunchPath_arguments (NSTask* THIS, NSString * path, NSArray * arguments) {
	NSLog(@"NSTask_launchedTaskWithLaunchPath_arguments");
	return [THIS launchedTaskWithLaunchPath:path arguments:arguments];
}

void NSTask_waitUntilExit (NSTask* THIS) {
	NSLog(@"NSTask_waitUntilExit");
	[THIS waitUntilExit];
}
NSTask * NSTask_alloc() {
	NSLog(@"NSTask_alloc()");
	return [NSTask alloc];
}
