/* Generated by genstubs.pl
 (c) 2004 kangaroo
*/

#include <Cocoa/Cocoa.h>

#include <Foundation/NSObject.h>

NSString * NSTimeZone_name (NSTimeZone* THIS) {
	NSLog(@"NSTimeZone_name");
	return [THIS name];
}
NSData * NSTimeZone_data (NSTimeZone* THIS) {
	NSLog(@"NSTimeZone_data");
	return [THIS data];
}
int NSTimeZone_secondsFromGMTForDate (NSTimeZone* THIS, NSDate * aDate) {
	NSLog(@"NSTimeZone_secondsFromGMTForDate");
	return [THIS secondsFromGMTForDate:aDate];
}

NSString * NSTimeZone_abbreviationForDate (NSTimeZone* THIS, NSDate * aDate) {
	NSLog(@"NSTimeZone_abbreviationForDate");
	return [THIS abbreviationForDate:aDate];
}

BOOL NSTimeZone_isDaylightSavingTimeForDate (NSTimeZone* THIS, NSDate * aDate) {
	NSLog(@"NSTimeZone_isDaylightSavingTimeForDate");
	return [THIS isDaylightSavingTimeForDate:aDate];
}

NSTimeZone * NSTimeZone_systemTimeZone (NSTimeZone* THIS) {
	NSLog(@"NSTimeZone_systemTimeZone");
	return [THIS systemTimeZone];
}
void NSTimeZone_resetSystemTimeZone (NSTimeZone* THIS) {
	NSLog(@"NSTimeZone_resetSystemTimeZone");
	[THIS resetSystemTimeZone];
}
NSTimeZone * NSTimeZone_defaultTimeZone (NSTimeZone* THIS) {
	NSLog(@"NSTimeZone_defaultTimeZone");
	return [THIS defaultTimeZone];
}
void NSTimeZone_setDefaultTimeZone (NSTimeZone* THIS, NSTimeZone * aTimeZone) {
	NSLog(@"NSTimeZone_setDefaultTimeZone");
	[THIS setDefaultTimeZone:aTimeZone];
}

NSTimeZone * NSTimeZone_localTimeZone (NSTimeZone* THIS) {
	NSLog(@"NSTimeZone_localTimeZone");
	return [THIS localTimeZone];
}
NSArray * NSTimeZone_knownTimeZoneNames (NSTimeZone* THIS) {
	NSLog(@"NSTimeZone_knownTimeZoneNames");
	return [THIS knownTimeZoneNames];
}
NSDictionary * NSTimeZone_abbreviationDictionary (NSTimeZone* THIS) {
	NSLog(@"NSTimeZone_abbreviationDictionary");
	return [THIS abbreviationDictionary];
}
int NSTimeZone_secondsFromGMT (NSTimeZone* THIS) {
	NSLog(@"NSTimeZone_secondsFromGMT");
	return [THIS secondsFromGMT];
}
NSString * NSTimeZone_abbreviation (NSTimeZone* THIS) {
	NSLog(@"NSTimeZone_abbreviation");
	return [THIS abbreviation];
}
BOOL NSTimeZone_isDaylightSavingTime (NSTimeZone* THIS) {
	NSLog(@"NSTimeZone_isDaylightSavingTime");
	return [THIS isDaylightSavingTime];
}
NSString * NSTimeZone_description (NSTimeZone* THIS) {
	NSLog(@"NSTimeZone_description");
	return [THIS description];
}
BOOL NSTimeZone_isEqualToTimeZone (NSTimeZone* THIS, NSTimeZone * aTimeZone) {
	NSLog(@"NSTimeZone_isEqualToTimeZone");
	return [THIS isEqualToTimeZone:aTimeZone];
}

NSTimeZone * NSTimeZone_timeZoneWithName (NSTimeZone* THIS, NSString * tzName) {
	NSLog(@"NSTimeZone_timeZoneWithName");
	return [THIS timeZoneWithName:tzName];
}

NSTimeZone * NSTimeZone_timeZoneWithName_data (NSTimeZone* THIS, NSString * tzName, NSData * aData) {
	NSLog(@"NSTimeZone_timeZoneWithName_data");
	return [THIS timeZoneWithName:tzName data:aData];
}

NSTimeZone * NSTimeZone_initWithName (NSTimeZone* THIS, NSString * tzName) {
	NSLog(@"NSTimeZone_initWithName");
	return [THIS initWithName:tzName];
}

NSTimeZone * NSTimeZone_initWithName_data (NSTimeZone* THIS, NSString * tzName, NSData * aData) {
	NSLog(@"NSTimeZone_initWithName_data");
	return [THIS initWithName:tzName data:aData];
}

NSTimeZone * NSTimeZone_timeZoneForSecondsFromGMT (NSTimeZone* THIS, int seconds) {
	NSLog(@"NSTimeZone_timeZoneForSecondsFromGMT");
	return [THIS timeZoneForSecondsFromGMT:seconds];
}

NSTimeZone * NSTimeZone_timeZoneWithAbbreviation (NSTimeZone* THIS, NSString * abbreviation) {
	NSLog(@"NSTimeZone_timeZoneWithAbbreviation");
	return [THIS timeZoneWithAbbreviation:abbreviation];
}

NSTimeZone * NSTimeZone_alloc() {
	NSLog(@"NSTimeZone_alloc()");
	return [NSTimeZone alloc];
}
