/* Generated by genstubs.pl
 * (c) 2004 kangaroo, C.J. and Urs
 */

#include <Cocoa/Cocoa.h>

#include <AvailabilityMacros.h>
#include <Foundation/NSObject.h>

NSURLCache * NSURLCache_initWithResponse_data (NSURLCache* THIS, NSURLResponse * response, NSData * data) {
	NSLog(@"NSURLCache_initWithResponse_data");
	return [THIS initWithResponse:response data:data];
}

NSURLCache * NSURLCache_initWithResponse_data_userInfo_storagePolicy (NSURLCache* THIS, NSURLResponse * response, NSData * data, NSDictionary * userInfo, NSURLCacheStoragePolicy storagePolicy) {
	NSLog(@"NSURLCache_initWithResponse_data_userInfo_storagePolicy");
	return [THIS initWithResponse:response data:data userInfo:userInfo storagePolicy:storagePolicy];
}

NSURLResponse * NSURLCache_response (NSURLCache* THIS) {
	NSLog(@"NSURLCache_response");
	return [THIS response];
}

NSData * NSURLCache_data (NSURLCache* THIS) {
	NSLog(@"NSURLCache_data");
	return [THIS data];
}

NSDictionary * NSURLCache_userInfo (NSURLCache* THIS) {
	NSLog(@"NSURLCache_userInfo");
	return [THIS userInfo];
}

NSURLCacheStoragePolicy NSURLCache_storagePolicy (NSURLCache* THIS) {
	NSLog(@"NSURLCache_storagePolicy");
	return [THIS storagePolicy];
}

NSURLCache * NSURLCache$_sharedURLCache () {
	NSLog(@"NSURLCache$_sharedURLCache");
	return [NSURLCache sharedURLCache];
}

void NSURLCache$_setSharedURLCache (NSURLCache * cache) {
	NSLog(@"NSURLCache$_setSharedURLCache");
	[NSURLCache setSharedURLCache:cache];
}

NSURLCache * NSURLCache_initWithMemoryCapacity_diskCapacity_diskPath (NSURLCache* THIS, unsigned memoryCapacity, unsigned diskCapacity, NSString * path) {
	NSLog(@"NSURLCache_initWithMemoryCapacity_diskCapacity_diskPath");
	return [THIS initWithMemoryCapacity:memoryCapacity diskCapacity:diskCapacity diskPath:path];
}

NSCachedURLResponse * NSURLCache_cachedResponseForRequest (NSURLCache* THIS, NSURLRequest * request) {
	NSLog(@"NSURLCache_cachedResponseForRequest");
	return [THIS cachedResponseForRequest:request];
}

void NSURLCache_storeCachedResponse_forRequest (NSURLCache* THIS, NSCachedURLResponse * cachedResponse, NSURLRequest * request) {
	NSLog(@"NSURLCache_storeCachedResponse_forRequest");
	[THIS storeCachedResponse:cachedResponse forRequest:request];
}

void NSURLCache_removeCachedResponseForRequest (NSURLCache* THIS, NSURLRequest * request) {
	NSLog(@"NSURLCache_removeCachedResponseForRequest");
	[THIS removeCachedResponseForRequest:request];
}

void NSURLCache_removeAllCachedResponses (NSURLCache* THIS) {
	NSLog(@"NSURLCache_removeAllCachedResponses");
	[THIS removeAllCachedResponses];
}

unsigned NSURLCache_memoryCapacity (NSURLCache* THIS) {
	NSLog(@"NSURLCache_memoryCapacity");
	return [THIS memoryCapacity];
}

unsigned NSURLCache_diskCapacity (NSURLCache* THIS) {
	NSLog(@"NSURLCache_diskCapacity");
	return [THIS diskCapacity];
}

void NSURLCache_setMemoryCapacity (NSURLCache* THIS, unsigned memoryCapacity) {
	NSLog(@"NSURLCache_setMemoryCapacity");
	[THIS setMemoryCapacity:memoryCapacity];
}

void NSURLCache_setDiskCapacity (NSURLCache* THIS, unsigned diskCapacity) {
	NSLog(@"NSURLCache_setDiskCapacity");
	[THIS setDiskCapacity:diskCapacity];
}

unsigned NSURLCache_currentMemoryUsage (NSURLCache* THIS) {
	NSLog(@"NSURLCache_currentMemoryUsage");
	return [THIS currentMemoryUsage];
}

unsigned NSURLCache_currentDiskUsage (NSURLCache* THIS) {
	NSLog(@"NSURLCache_currentDiskUsage");
	return [THIS currentDiskUsage];
}

NSURLCache * NSURLCache_alloc(){
	NSLog(@"NSURLCache_alloc()");
	return [ NSURLCache alloc ];
}