/* Generated by genstubs.pl
 (c) 2004 kangaroo
*/

#include <Cocoa/Cocoa.h>

#include <AvailabilityMacros.h>

NSURLError * NSURLError_alloc() {
	NSLog(@"NSURLError_alloc()");
	return [NSURLError alloc];
}
