/* Generated by genstubs.pl
 * (c) 2004 kangaroo, C.J. and Urs
 */

#include <Cocoa/Cocoa.h>

#include <AvailabilityMacros.h>
#include <Foundation/NSObject.h>

NSURLCredentialStorage * NSURLCredentialStorage$_sharedCredentialStorage () {
	NSLog(@"NSURLCredentialStorage$_sharedCredentialStorage");
	return [NSURLCredentialStorage sharedCredentialStorage];
}

NSDictionary * NSURLCredentialStorage_credentialsForProtectionSpace (NSURLCredentialStorage* THIS, NSURLProtectionSpace * space) {
	NSLog(@"NSURLCredentialStorage_credentialsForProtectionSpace");
	return [THIS credentialsForProtectionSpace:space];
}

NSDictionary * NSURLCredentialStorage_allCredentials (NSURLCredentialStorage* THIS) {
	NSLog(@"NSURLCredentialStorage_allCredentials");
	return [THIS allCredentials];
}

void NSURLCredentialStorage_setCredential_forProtectionSpace (NSURLCredentialStorage* THIS, NSURLCredential * credential, NSURLProtectionSpace * space) {
	NSLog(@"NSURLCredentialStorage_setCredential_forProtectionSpace");
	[THIS setCredential:credential forProtectionSpace:space];
}

void NSURLCredentialStorage_removeCredential_forProtectionSpace (NSURLCredentialStorage* THIS, NSURLCredential * credential, NSURLProtectionSpace * space) {
	NSLog(@"NSURLCredentialStorage_removeCredential_forProtectionSpace");
	[THIS removeCredential:credential forProtectionSpace:space];
}

NSURLCredential * NSURLCredentialStorage_defaultCredentialForProtectionSpace (NSURLCredentialStorage* THIS, NSURLProtectionSpace * space) {
	NSLog(@"NSURLCredentialStorage_defaultCredentialForProtectionSpace");
	return [THIS defaultCredentialForProtectionSpace:space];
}

void NSURLCredentialStorage_setDefaultCredential_forProtectionSpace (NSURLCredentialStorage* THIS, NSURLCredential * credential, NSURLProtectionSpace * space) {
	NSLog(@"NSURLCredentialStorage_setDefaultCredential_forProtectionSpace");
	[THIS setDefaultCredential:credential forProtectionSpace:space];
}

NSURLCredentialStorage * NSURLCredentialStorage_alloc(){
	NSLog(@"NSURLCredentialStorage_alloc()");
	return [ NSURLCredentialStorage alloc ];
}