/* Generated by genstubs.pl
 * (c) 2004 kangaroo, C.J. and Urs
 */

#include <Cocoa/Cocoa.h>

#warning #include the individual headers (that you need) listed in this header instead.
#include <Foundation/NSString.h>
#include <Foundation/NSDictionary.h>
#include <Foundation/NSEnumerator.h>

NSUtilities * NSUtilities_alloc(){
	NSLog(@"NSUtilities_alloc()");
	return [ NSUtilities alloc ];
}