/* Generated by genstubs.pl
 * (c) 2004 kangaroo, C.J. and Urs
 */

#include <Cocoa/Cocoa.h>

#include <Foundation/NSObject.h>

void NSValueTransformer$_setValueTransformer_forName (NSValueTransformer * transformer, NSString * name) {
	NSLog(@"NSValueTransformer$_setValueTransformer_forName");
	[NSValueTransformer setValueTransformer:transformer forName:name];
}

NSValueTransformer * NSValueTransformer$_valueTransformerForName (NSString * name) {
	NSLog(@"NSValueTransformer$_valueTransformerForName");
	return [NSValueTransformer valueTransformerForName:name];
}

NSArray * NSValueTransformer$_valueTransformerNames () {
	NSLog(@"NSValueTransformer$_valueTransformerNames");
	return [NSValueTransformer valueTransformerNames];
}

Class NSValueTransformer$_transformedValueClass () {
	NSLog(@"NSValueTransformer$_transformedValueClass");
	return [NSValueTransformer transformedValueClass];
}

BOOL NSValueTransformer$_allowsReverseTransformation () {
	NSLog(@"NSValueTransformer$_allowsReverseTransformation");
	return [NSValueTransformer allowsReverseTransformation];
}

NSValueTransformer * NSValueTransformer_transformedValue (NSValueTransformer* THIS, id value) {
	NSLog(@"NSValueTransformer_transformedValue");
	return [THIS transformedValue:value];
}

NSValueTransformer * NSValueTransformer_reverseTransformedValue (NSValueTransformer* THIS, id value) {
	NSLog(@"NSValueTransformer_reverseTransformedValue");
	return [THIS reverseTransformedValue:value];
}

NSValueTransformer * NSValueTransformer_alloc(){
	NSLog(@"NSValueTransformer_alloc()");
	return [ NSValueTransformer alloc ];
}