//
//  Element.cs
//
//  Authors
//    - Kangaroo, Geoff Norton
//    - C.J. Collier, Collier Technologies, <cjcollier@colliertech.org>
//    - Urs C. Muff, Quark Inc., <umuff@quark.com>
//    - Adham Findlay
//
//  Copyright (c) 2004 Quark Inc. and Collier Technologies.  All rights reserved.
//
//	$Header: /home/miguel/third-conversion/public/cocoa-sharp/generator/Attic/Element.cs,v 1.3 2004/06/23 17:14:20 gnorton Exp $
//

using System;
using System.Collections;
using System.IO;
using System.Text.RegularExpressions;

namespace ObjCManagedExporter 
{

	public abstract class Element 
	{
		protected string mOriginal;
		private string mName;
		private string mFramework;
        
		public Element(string _original, string _name, string _framework) 
		{
			mOriginal = _original;
			mName = _name;
			mFramework = _framework;
		}
        
		public string Name 
		{
			get { return mName; }
			set { mName = value; }
		}

		public string Framework 
		{
			get { return mFramework; }
		}

		public virtual string FileNameFormat
		{
			get { return "{1}{0}{2}.gen.cs"; }
		}

		internal static TextWriter OpenFile(string pathFormat,string fileFormat,string frmwrk,string file)
		{
			string path = string.Format(pathFormat, Path.DirectorySeparatorChar, frmwrk);
			if (!Directory.Exists(path))
				Directory.CreateDirectory(path);
			TextWriter ret = new StreamWriter(File.Create(string.Format(fileFormat, Path.DirectorySeparatorChar, path, file)));
			ret.WriteLine("// Generated by Cocoa# Glue Generator @ " + DateTime.Now);
			ret.WriteLine();
			return ret;
		}

		public TextWriter OpenFile()
		{
			return OpenFile("src{0}Apple.{1}", this.FileNameFormat, Framework, Name);
		}

		public void WriteFile(Configuration config)
		{
			TextWriter _cs = OpenFile();
			WriteCS(_cs, config);
			_cs.Close();
		}

		public abstract void WriteCS(TextWriter _cs, Configuration config);

		public void ProcessAddin(TextWriter _cs, Configuration config)
		{
			if(File.Exists(String.Format("{0}{1}{2}{1}{3}.addin", config.AddinPath, Path.DirectorySeparatorChar, Framework, Name))) 
			{
				_cs.WriteLine("\t\t#region -- Generator Addins --");
				StreamReader _addinReader = new StreamReader(String.Format("{0}{1}{2}{1}{3}.addin", config.AddinPath, Path.DirectorySeparatorChar, Framework, Name));
				String _addinLine;
				while( (_addinLine = _addinReader.ReadLine()) != null )
				{
					_cs.WriteLine(_addinLine);
				}
				_addinReader.Close();
				_cs.WriteLine("\t\t#endregion");
			}
		}
	}

	public abstract class ElementWithMethods : Element
	{
		private IDictionary mMethods;
		private static Regex mMethodRegex = new Regex(@"\s*([+-])\s*(?:\(([^\)]+)\))?(.+)");

		public ElementWithMethods(string _name, string _framework) : base(string.Empty,_name,_framework) 
		{
			mMethods = new Hashtable();
		}

		public IDictionary Methods 
		{
			get { return mMethods; }
		}
        
		public void AddMethods(string methods) 
		{
			string[] splitMethods = methods.Split('\n');
			foreach(string method in splitMethods) 
				if(mMethodRegex.IsMatch(method) && mMethods[method] == null)
					mMethods.Add(method, new Method(method));
		}

	}
}

//	$Log: Element.cs,v $
//	Revision 1.3  2004/06/23 17:14:20  gnorton
//	Custom addins supported on a per file basis.
//
//	Revision 1.2  2004/06/23 15:29:29  urs
//	Major refactor, allow inheriting parent constructors
//	
//	Revision 1.1  2004/06/22 13:38:59  urs
//	More cleanup and refactoring start
//	Make output actually compile (diverse fixes)
//	
//	Revision 1.3  2004/06/22 12:04:12  urs
//	Cleanup, Headers, -out:[CS|OC], VS proj
//	
//
