// Generated by Cocoa# Glue Generator @ 06/24/2004 16:45:29

using System;
using System.Collections;
using System.Runtime.InteropServices;
using Apple.Tools;

namespace Apple.Foundation {
    public class NSConcreteNotification : NSNotification {
        #region -- Internal Members --
        protected internal static IntPtr _NSConcreteNotification_classPtr;
        protected internal static IntPtr NSConcreteNotification_classPtr { get { if (_NSConcreteNotification_classPtr == IntPtr.Zero) _NSConcreteNotification_classPtr = Class.Get("NSConcreteNotification"); return _NSConcreteNotification_classPtr; } }
        #endregion

        #region -- Properties --
        #endregion

        #region -- Constructors --
        protected internal NSConcreteNotification(IntPtr raw,bool release) : base(raw,release) {}

        public NSConcreteNotification() : this(NSObject__alloc0(NSConcreteNotification_classPtr),true) {}
        #endregion

    }
}
