// Generated by Cocoa# Glue Generator @ 01/12/2005 22:16:28

using System;
namespace Apple.AppKit {
    public enum _noname_19 : uint {
        NSDragOperationNone = 0,
        NSDragOperationCopy = 1,
        NSDragOperationLink = 2,
        NSDragOperationGeneric = 4,
        NSDragOperationPrivate = 8,
        NSDragOperationAll_Obsolete = 15,
        NSDragOperationMove = 16,
        NSDragOperationDelete = 32,
        NSDragOperationEvery = UINT_MAX,
        UINT_MAX = uint.MaxValue,
    }
}
