/* Generated by genstubs.pl
 * (c) 2004 kangaroo, C.J. and Urs
 */

#include <Cocoa/Cocoa.h>

#include <AvailabilityMacros.h>

AppKitDefines * AppKitDefines_alloc(){
	NSLog(@"AppKitDefines_alloc()");
	return [ AppKitDefines alloc ];
}