/* Generated by genstubs.pl
 (c) 2004 kangaroo
*/

#include <Cocoa/Cocoa.h>

#include <AppKit/AppKitDefines.h>

#include <AppKit/NSErrors.h>

#include <Foundation/NSGeometry.h>

#include <Foundation/NSObject.h>

NSArray * NSAccessibility_accessibilityAttributeNames (NSAccessibility* THIS) {
	NSLog(@"NSAccessibility_accessibilityAttributeNames");
	return [THIS accessibilityAttributeNames];
}
NSAccessibility * NSAccessibility_accessibilityAttributeValue (NSAccessibility* THIS, NSString * attribute) {
	NSLog(@"NSAccessibility_accessibilityAttributeValue");
	return [THIS accessibilityAttributeValue:attribute];
}

BOOL NSAccessibility_accessibilityIsAttributeSettable (NSAccessibility* THIS, NSString * attribute) {
	NSLog(@"NSAccessibility_accessibilityIsAttributeSettable");
	return [THIS accessibilityIsAttributeSettable:attribute];
}

void NSAccessibility_accessibilitySetValue_forAttribute (NSAccessibility* THIS, NSAccessibility * value, NSString * attribute) {
	NSLog(@"NSAccessibility_accessibilitySetValue_forAttribute");
	[THIS accessibilitySetValue:value forAttribute:attribute];
}

NSArray * NSAccessibility_accessibilityParameterizedAttributeNames (NSAccessibility* THIS) {
	NSLog(@"NSAccessibility_accessibilityParameterizedAttributeNames");
	return [THIS accessibilityParameterizedAttributeNames];
}
NSAccessibility * NSAccessibility_accessibilityAttributeValue_forParameter (NSAccessibility* THIS, NSString * attribute, NSAccessibility * parameter) {
	NSLog(@"NSAccessibility_accessibilityAttributeValue_forParameter");
	return [THIS accessibilityAttributeValue:attribute forParameter:parameter];
}

NSArray * NSAccessibility_accessibilityActionNames (NSAccessibility* THIS) {
	NSLog(@"NSAccessibility_accessibilityActionNames");
	return [THIS accessibilityActionNames];
}
NSString * NSAccessibility_accessibilityActionDescription (NSAccessibility* THIS, NSString * action) {
	NSLog(@"NSAccessibility_accessibilityActionDescription");
	return [THIS accessibilityActionDescription:action];
}

void NSAccessibility_accessibilityPerformAction (NSAccessibility* THIS, NSString * action) {
	NSLog(@"NSAccessibility_accessibilityPerformAction");
	[THIS accessibilityPerformAction:action];
}

BOOL NSAccessibility_accessibilityIsIgnored (NSAccessibility* THIS) {
	NSLog(@"NSAccessibility_accessibilityIsIgnored");
	return [THIS accessibilityIsIgnored];
}
NSAccessibility * NSAccessibility_accessibilityHitTest (NSAccessibility* THIS, NSPoint point) {
	NSLog(@"NSAccessibility_accessibilityHitTest");
	return [THIS accessibilityHitTest:point];
}

NSAccessibility * NSAccessibility_accessibilityFocusedUIElement (NSAccessibility* THIS) {
	NSLog(@"NSAccessibility_accessibilityFocusedUIElement");
	return [THIS accessibilityFocusedUIElement];
}
NSAccessibility * NSAccessibility_alloc() {
	NSLog(@"NSAccessibility_alloc()");
	return [NSAccessibility alloc];
}
