/* Generated by genstubs.pl
 * (c) 2004 kangaroo, C.J. and Urs
 */

#include <Cocoa/Cocoa.h>

#include <Foundation/NSAppleScript.h>

NSAttributedString * NSAppleScriptExtensions_richTextSource (NSAppleScriptExtensions* THIS) {
	NSLog(@"NSAppleScriptExtensions_richTextSource");
	return [THIS richTextSource];
}

NSAppleScriptExtensions * NSAppleScriptExtensions_alloc(){
	NSLog(@"NSAppleScriptExtensions_alloc()");
	return [ NSAppleScriptExtensions alloc ];
}