/* Generated by genstubs.pl
 * (c) 2004 kangaroo, C.J. and Urs
 */

#include <Cocoa/Cocoa.h>

#include <AppKit/NSImageRep.h>
#include <AppKit/NSGraphics.h>

NSCachedImageRep * NSCachedImageRep_initWithWindow_rect (NSCachedImageRep* THIS, NSWindow * win, NSRect rect) {
	NSLog(@"NSCachedImageRep_initWithWindow_rect");
	return [THIS initWithWindow:win rect:rect];
}

NSCachedImageRep * NSCachedImageRep_initWithSize_depth_separate_alpha (NSCachedImageRep* THIS, NSSize size, NSWindowDepth depth, BOOL flag, BOOL alpha) {
	NSLog(@"NSCachedImageRep_initWithSize_depth_separate_alpha");
	return [THIS initWithSize:size depth:depth separate:flag alpha:alpha];
}

NSWindow * NSCachedImageRep_window (NSCachedImageRep* THIS) {
	NSLog(@"NSCachedImageRep_window");
	return [THIS window];
}

NSRect NSCachedImageRep_rect (NSCachedImageRep* THIS) {
	NSLog(@"NSCachedImageRep_rect");
	return [THIS rect];
}

NSCachedImageRep * NSCachedImageRep_alloc(){
	NSLog(@"NSCachedImageRep_alloc()");
	return [ NSCachedImageRep alloc ];
}