/* Generated by genstubs.pl
 * (c) 2004 kangaroo, C.J. and Urs
 */

#include <Cocoa/Cocoa.h>

#include <AppKit/NSKeyValueBinding.h>
#include <CoreFoundation/CoreFoundation.h>

void NSController_objectDidBeginEditing (NSController* THIS, id editor) {
	NSLog(@"NSController_objectDidBeginEditing");
	[THIS objectDidBeginEditing:editor];
}

void NSController_objectDidEndEditing (NSController* THIS, id editor) {
	NSLog(@"NSController_objectDidEndEditing");
	[THIS objectDidEndEditing:editor];
}

void NSController_discardEditing (NSController* THIS) {
	NSLog(@"NSController_discardEditing");
	[THIS discardEditing];
}

BOOL NSController_commitEditing (NSController* THIS) {
	NSLog(@"NSController_commitEditing");
	return [THIS commitEditing];
}

BOOL NSController_isEditing (NSController* THIS) {
	NSLog(@"NSController_isEditing");
	return [THIS isEditing];
}

NSController * NSController_alloc(){
	NSLog(@"NSController_alloc()");
	return [ NSController alloc ];
}