/* Generated by genstubs.pl
 * (c) 2004 kangaroo, C.J. and Urs
 */

#include <Cocoa/Cocoa.h>

#include <AppKit/NSDocument.h>

NSString * NSDocumentScripting_lastComponentOfFileName (NSDocumentScripting* THIS) {
	NSLog(@"NSDocumentScripting_lastComponentOfFileName");
	return [THIS lastComponentOfFileName];
}

void NSDocumentScripting_setLastComponentOfFileName (NSDocumentScripting* THIS, NSString * str) {
	NSLog(@"NSDocumentScripting_setLastComponentOfFileName");
	[THIS setLastComponentOfFileName:str];
}

NSDocumentScripting * NSDocumentScripting_handleSaveScriptCommand (NSDocumentScripting* THIS, NSScriptCommand * command) {
	NSLog(@"NSDocumentScripting_handleSaveScriptCommand");
	return [THIS handleSaveScriptCommand:command];
}

NSDocumentScripting * NSDocumentScripting_handleCloseScriptCommand (NSDocumentScripting* THIS, NSCloseCommand * command) {
	NSLog(@"NSDocumentScripting_handleCloseScriptCommand");
	return [THIS handleCloseScriptCommand:command];
}

NSDocumentScripting * NSDocumentScripting_handlePrintScriptCommand (NSDocumentScripting* THIS, NSScriptCommand * command) {
	NSLog(@"NSDocumentScripting_handlePrintScriptCommand");
	return [THIS handlePrintScriptCommand:command];
}

NSScriptObjectSpecifier * NSDocumentScripting_objectSpecifier (NSDocumentScripting* THIS) {
	NSLog(@"NSDocumentScripting_objectSpecifier");
	return [THIS objectSpecifier];
}

NSDocumentScripting * NSDocumentScripting_alloc(){
	NSLog(@"NSDocumentScripting_alloc()");
	return [ NSDocumentScripting alloc ];
}