/* Generated by genstubs.pl
 * (c) 2004 kangaroo, C.J. and Urs
 */

#include <Cocoa/Cocoa.h>

#include <AppKit/NSMatrix.h>

int NSForm_indexOfSelectedItem (NSForm* THIS) {
	NSLog(@"NSForm_indexOfSelectedItem");
	return [THIS indexOfSelectedItem];
}

void NSForm_setEntryWidth (NSForm* THIS, float width) {
	NSLog(@"NSForm_setEntryWidth");
	[THIS setEntryWidth:width];
}

void NSForm_setInterlineSpacing (NSForm* THIS, float spacing) {
	NSLog(@"NSForm_setInterlineSpacing");
	[THIS setInterlineSpacing:spacing];
}

void NSForm_setBordered (NSForm* THIS, BOOL flag) {
	NSLog(@"NSForm_setBordered");
	[THIS setBordered:flag];
}

void NSForm_setBezeled (NSForm* THIS, BOOL flag) {
	NSLog(@"NSForm_setBezeled");
	[THIS setBezeled:flag];
}

void NSForm_setTitleAlignment (NSForm* THIS, NSTextAlignment mode) {
	NSLog(@"NSForm_setTitleAlignment");
	[THIS setTitleAlignment:mode];
}

void NSForm_setTextAlignment (NSForm* THIS, int mode) {
	NSLog(@"NSForm_setTextAlignment");
	[THIS setTextAlignment:mode];
}

void NSForm_setTitleFont (NSForm* THIS, NSFont * fontObj) {
	NSLog(@"NSForm_setTitleFont");
	[THIS setTitleFont:fontObj];
}

void NSForm_setTextFont (NSForm* THIS, NSFont * fontObj) {
	NSLog(@"NSForm_setTextFont");
	[THIS setTextFont:fontObj];
}

NSForm * NSForm_cellAtIndex (NSForm* THIS, int index) {
	NSLog(@"NSForm_cellAtIndex");
	return [THIS cellAtIndex:index];
}

void NSForm_drawCellAtIndex (NSForm* THIS, int index) {
	NSLog(@"NSForm_drawCellAtIndex");
	[THIS drawCellAtIndex:index];
}

NSFormCell * NSForm_addEntry (NSForm* THIS, NSString * title) {
	NSLog(@"NSForm_addEntry");
	return [THIS addEntry:title];
}

NSFormCell * NSForm_insertEntry_atIndex (NSForm* THIS, NSString * title, int index) {
	NSLog(@"NSForm_insertEntry_atIndex");
	return [THIS insertEntry:title atIndex:index];
}

void NSForm_removeEntryAtIndex (NSForm* THIS, int index) {
	NSLog(@"NSForm_removeEntryAtIndex");
	[THIS removeEntryAtIndex:index];
}

int NSForm_indexOfCellWithTag (NSForm* THIS, int aTag) {
	NSLog(@"NSForm_indexOfCellWithTag");
	return [THIS indexOfCellWithTag:aTag];
}

void NSForm_selectTextAtIndex (NSForm* THIS, int index) {
	NSLog(@"NSForm_selectTextAtIndex");
	[THIS selectTextAtIndex:index];
}

void NSForm_setFrameSize (NSForm* THIS, NSSize newSize) {
	NSLog(@"NSForm_setFrameSize");
	[THIS setFrameSize:newSize];
}

NSForm * NSForm_alloc(){
	NSLog(@"NSForm_alloc()");
	return [ NSForm alloc ];
}