/* Generated by genstubs.pl
 (c) 2004 kangaroo
*/

#include <Cocoa/Cocoa.h>

#include <AppKit/NSButtonCell.h>

#include <AppKit/NSMenu.h>

#include <AppKit/NSMenuItem.h>

void NSMenuItemCell_setMenuItem (NSMenuItemCell* THIS, NSMenuItem * item) {
	NSLog(@"NSMenuItemCell_setMenuItem");
	[THIS setMenuItem:item];
}

NSMenuItem * NSMenuItemCell_menuItem (NSMenuItemCell* THIS) {
	NSLog(@"NSMenuItemCell_menuItem");
	return [THIS menuItem];
}
void NSMenuItemCell_setMenuView (NSMenuItemCell* THIS, NSMenuView * menuView) {
	NSLog(@"NSMenuItemCell_setMenuView");
	[THIS setMenuView:menuView];
}

NSMenuView * NSMenuItemCell_menuView (NSMenuItemCell* THIS) {
	NSLog(@"NSMenuItemCell_menuView");
	return [THIS menuView];
}
void NSMenuItemCell_setHighlighted (NSMenuItemCell* THIS, BOOL flag) {
	NSLog(@"NSMenuItemCell_setHighlighted");
	[THIS setHighlighted:flag];
}

BOOL NSMenuItemCell_isHighlighted (NSMenuItemCell* THIS) {
	NSLog(@"NSMenuItemCell_isHighlighted");
	return [THIS isHighlighted];
}
void NSMenuItemCell_setNeedsSizing (NSMenuItemCell* THIS, BOOL flag) {
	NSLog(@"NSMenuItemCell_setNeedsSizing");
	[THIS setNeedsSizing:flag];
}

BOOL NSMenuItemCell_needsSizing (NSMenuItemCell* THIS) {
	NSLog(@"NSMenuItemCell_needsSizing");
	return [THIS needsSizing];
}
void NSMenuItemCell_calcSize (NSMenuItemCell* THIS) {
	NSLog(@"NSMenuItemCell_calcSize");
	[THIS calcSize];
}
void NSMenuItemCell_setNeedsDisplay (NSMenuItemCell* THIS, BOOL flag) {
	NSLog(@"NSMenuItemCell_setNeedsDisplay");
	[THIS setNeedsDisplay:flag];
}

BOOL NSMenuItemCell_needsDisplay (NSMenuItemCell* THIS) {
	NSLog(@"NSMenuItemCell_needsDisplay");
	return [THIS needsDisplay];
}
float NSMenuItemCell_stateImageWidth (NSMenuItemCell* THIS) {
	NSLog(@"NSMenuItemCell_stateImageWidth");
	return [THIS stateImageWidth];
}
float NSMenuItemCell_imageWidth (NSMenuItemCell* THIS) {
	NSLog(@"NSMenuItemCell_imageWidth");
	return [THIS imageWidth];
}
float NSMenuItemCell_titleWidth (NSMenuItemCell* THIS) {
	NSLog(@"NSMenuItemCell_titleWidth");
	return [THIS titleWidth];
}
float NSMenuItemCell_keyEquivalentWidth (NSMenuItemCell* THIS) {
	NSLog(@"NSMenuItemCell_keyEquivalentWidth");
	return [THIS keyEquivalentWidth];
}
NSRect NSMenuItemCell_stateImageRectForBounds (NSMenuItemCell* THIS, NSRect cellFrame) {
	NSLog(@"NSMenuItemCell_stateImageRectForBounds");
	return [THIS stateImageRectForBounds:cellFrame];
}

NSRect NSMenuItemCell_imageRectForBounds (NSMenuItemCell* THIS, NSRect cellFrame) {
	NSLog(@"NSMenuItemCell_imageRectForBounds");
	return [THIS imageRectForBounds:cellFrame];
}

NSRect NSMenuItemCell_titleRectForBounds (NSMenuItemCell* THIS, NSRect cellFrame) {
	NSLog(@"NSMenuItemCell_titleRectForBounds");
	return [THIS titleRectForBounds:cellFrame];
}

NSRect NSMenuItemCell_keyEquivalentRectForBounds (NSMenuItemCell* THIS, NSRect cellFrame) {
	NSLog(@"NSMenuItemCell_keyEquivalentRectForBounds");
	return [THIS keyEquivalentRectForBounds:cellFrame];
}

void NSMenuItemCell_drawSeparatorItemWithFrame_inView (NSMenuItemCell* THIS, NSRect cellFrame, NSView * controlView) {
	NSLog(@"NSMenuItemCell_drawSeparatorItemWithFrame_inView");
	[THIS drawSeparatorItemWithFrame:cellFrame inView:controlView];
}

void NSMenuItemCell_drawStateImageWithFrame_inView (NSMenuItemCell* THIS, NSRect cellFrame, NSView * controlView) {
	NSLog(@"NSMenuItemCell_drawStateImageWithFrame_inView");
	[THIS drawStateImageWithFrame:cellFrame inView:controlView];
}

void NSMenuItemCell_drawImageWithFrame_inView (NSMenuItemCell* THIS, NSRect cellFrame, NSView * controlView) {
	NSLog(@"NSMenuItemCell_drawImageWithFrame_inView");
	[THIS drawImageWithFrame:cellFrame inView:controlView];
}

void NSMenuItemCell_drawTitleWithFrame_inView (NSMenuItemCell* THIS, NSRect cellFrame, NSView * controlView) {
	NSLog(@"NSMenuItemCell_drawTitleWithFrame_inView");
	[THIS drawTitleWithFrame:cellFrame inView:controlView];
}

void NSMenuItemCell_drawKeyEquivalentWithFrame_inView (NSMenuItemCell* THIS, NSRect cellFrame, NSView * controlView) {
	NSLog(@"NSMenuItemCell_drawKeyEquivalentWithFrame_inView");
	[THIS drawKeyEquivalentWithFrame:cellFrame inView:controlView];
}

void NSMenuItemCell_drawBorderAndBackgroundWithFrame_inView (NSMenuItemCell* THIS, NSRect cellFrame, NSView * controlView) {
	NSLog(@"NSMenuItemCell_drawBorderAndBackgroundWithFrame_inView");
	[THIS drawBorderAndBackgroundWithFrame:cellFrame inView:controlView];
}

NSMenuItemCell * NSMenuItemCell_alloc() {
	NSLog(@"NSMenuItemCell_alloc()");
	return [NSMenuItemCell alloc];
}
