/* Generated by genstubs.pl
 (c) 2004 kangaroo
*/

#include <Cocoa/Cocoa.h>

#include <AppKit/NSView.h>

void NSMovieView_setMovie (NSMovieView* THIS, NSMovie* movie) {
	NSLog(@"NSMovieView_setMovie");
	[THIS setMovie:movie];
}

NSMovie* NSMovieView_movie (NSMovieView* THIS) {
	NSLog(@"NSMovieView_movie");
	return [THIS movie];
}
/* UNSUPPORTED: 
- (void* *MovieController*) movieController;
 */

NSRect NSMovieView_movieRect (NSMovieView* THIS) {
	NSLog(@"NSMovieView_movieRect");
	return [THIS movieRect];
}
void NSMovieView_start (NSMovieView* THIS, NSMovieView * sender) {
	NSLog(@"NSMovieView_start");
	[THIS start:sender];
}

void NSMovieView_stop (NSMovieView* THIS, NSMovieView * sender) {
	NSLog(@"NSMovieView_stop");
	[THIS stop:sender];
}

BOOL NSMovieView_isPlaying (NSMovieView* THIS) {
	NSLog(@"NSMovieView_isPlaying");
	return [THIS isPlaying];
}
void NSMovieView_gotoPosterFrame (NSMovieView* THIS, NSMovieView * sender) {
	NSLog(@"NSMovieView_gotoPosterFrame");
	[THIS gotoPosterFrame:sender];
}

void NSMovieView_gotoBeginning (NSMovieView* THIS, NSMovieView * sender) {
	NSLog(@"NSMovieView_gotoBeginning");
	[THIS gotoBeginning:sender];
}

void NSMovieView_gotoEnd (NSMovieView* THIS, NSMovieView * sender) {
	NSLog(@"NSMovieView_gotoEnd");
	[THIS gotoEnd:sender];
}

void NSMovieView_stepForward (NSMovieView* THIS, NSMovieView * sender) {
	NSLog(@"NSMovieView_stepForward");
	[THIS stepForward:sender];
}

void NSMovieView_stepBack (NSMovieView* THIS, NSMovieView * sender) {
	NSLog(@"NSMovieView_stepBack");
	[THIS stepBack:sender];
}

void NSMovieView_setRate (NSMovieView* THIS, float rate) {
	NSLog(@"NSMovieView_setRate");
	[THIS setRate:rate];
}

float NSMovieView_rate (NSMovieView* THIS) {
	NSLog(@"NSMovieView_rate");
	return [THIS rate];
}
void NSMovieView_setVolume (NSMovieView* THIS, float volume) {
	NSLog(@"NSMovieView_setVolume");
	[THIS setVolume:volume];
}

float NSMovieView_volume (NSMovieView* THIS) {
	NSLog(@"NSMovieView_volume");
	return [THIS volume];
}
void NSMovieView_setMuted (NSMovieView* THIS, BOOL mute) {
	NSLog(@"NSMovieView_setMuted");
	[THIS setMuted:mute];
}

BOOL NSMovieView_isMuted (NSMovieView* THIS) {
	NSLog(@"NSMovieView_isMuted");
	return [THIS isMuted];
}
void NSMovieView_setLoopMode (NSMovieView* THIS, NSQTMovieLoopMode mode) {
	NSLog(@"NSMovieView_setLoopMode");
	[THIS setLoopMode:mode];
}

NSQTMovieLoopMode NSMovieView_loopMode (NSMovieView* THIS) {
	NSLog(@"NSMovieView_loopMode");
	return [THIS loopMode];
}
void NSMovieView_setPlaysSelectionOnly (NSMovieView* THIS, BOOL flag) {
	NSLog(@"NSMovieView_setPlaysSelectionOnly");
	[THIS setPlaysSelectionOnly:flag];
}

BOOL NSMovieView_playsSelectionOnly (NSMovieView* THIS) {
	NSLog(@"NSMovieView_playsSelectionOnly");
	return [THIS playsSelectionOnly];
}
void NSMovieView_setPlaysEveryFrame (NSMovieView* THIS, BOOL flag) {
	NSLog(@"NSMovieView_setPlaysEveryFrame");
	[THIS setPlaysEveryFrame:flag];
}

BOOL NSMovieView_playsEveryFrame (NSMovieView* THIS) {
	NSLog(@"NSMovieView_playsEveryFrame");
	return [THIS playsEveryFrame];
}
void NSMovieView_showController_adjustingSize (NSMovieView* THIS, BOOL show, BOOL adjustSize) {
	NSLog(@"NSMovieView_showController_adjustingSize");
	[THIS showController:show adjustingSize:adjustSize];
}

BOOL NSMovieView_isControllerVisible (NSMovieView* THIS) {
	NSLog(@"NSMovieView_isControllerVisible");
	return [THIS isControllerVisible];
}
void NSMovieView_resizeWithMagnification (NSMovieView* THIS, float magnification) {
	NSLog(@"NSMovieView_resizeWithMagnification");
	[THIS resizeWithMagnification:magnification];
}

NSSize NSMovieView_sizeForMagnification (NSMovieView* THIS, float magnification) {
	NSLog(@"NSMovieView_sizeForMagnification");
	return [THIS sizeForMagnification:magnification];
}

void NSMovieView_setEditable (NSMovieView* THIS, BOOL editable) {
	NSLog(@"NSMovieView_setEditable");
	[THIS setEditable:editable];
}

BOOL NSMovieView_isEditable (NSMovieView* THIS) {
	NSLog(@"NSMovieView_isEditable");
	return [THIS isEditable];
}
void NSMovieView_cut (NSMovieView* THIS, NSMovieView * sender) {
	NSLog(@"NSMovieView_cut");
	[THIS cut:sender];
}

void NSMovieView_copy (NSMovieView* THIS, NSMovieView * sender) {
	NSLog(@"NSMovieView_copy");
	[THIS copy:sender];
}

void NSMovieView_paste (NSMovieView* THIS, NSMovieView * sender) {
	NSLog(@"NSMovieView_paste");
	[THIS paste:sender];
}

void NSMovieView_delete (NSMovieView* THIS, NSMovieView * sender) {
	NSLog(@"NSMovieView_delete");
	[THIS delete:sender];
}

void NSMovieView_selectAll (NSMovieView* THIS, NSMovieView * sender) {
	NSLog(@"NSMovieView_selectAll");
	[THIS selectAll:sender];
}

void NSMovieView_clear (NSMovieView* THIS, NSMovieView * sender) {
	NSLog(@"NSMovieView_clear");
	[THIS clear:sender];
}

NSMovieView * NSMovieView_alloc() {
	NSLog(@"NSMovieView_alloc()");
	return [NSMovieView alloc];
}
