/* Generated by genstubs.pl
 (c) 2004 kangaroo
*/

#include <Cocoa/Cocoa.h>

NSNibDeclarations * NSNibDeclarations_alloc() {
	NSLog(@"NSNibDeclarations_alloc()");
	return [NSNibDeclarations alloc];
}
