/* Generated by genstubs.pl
 (c) 2004 kangaroo
*/

#include <Cocoa/Cocoa.h>

#include <Foundation/NSBundle.h>

BOOL NSNibLoading_loadNibFile_externalNameTable_withZone (NSNibLoading* THIS, NSString * fileName, NSDictionary * context, NSZone * zone) {
	NSLog(@"NSNibLoading_loadNibFile_externalNameTable_withZone");
	return [THIS loadNibFile:fileName externalNameTable:context withZone:zone];
}

BOOL NSNibLoading_loadNibNamed_owner (NSNibLoading* THIS, NSString * nibName, NSNibLoading * owner) {
	NSLog(@"NSNibLoading_loadNibNamed_owner");
	return [THIS loadNibNamed:nibName owner:owner];
}

BOOL NSNibLoading_loadNibFile_externalNameTable_withZone (NSNibLoading* THIS, NSString * fileName, NSDictionary * context, NSZone * zone) {
	NSLog(@"NSNibLoading_loadNibFile_externalNameTable_withZone");
	return [THIS loadNibFile:fileName externalNameTable:context withZone:zone];
}

void NSNibLoading_awakeFromNib (NSNibLoading* THIS) {
	NSLog(@"NSNibLoading_awakeFromNib");
	[THIS awakeFromNib];
}
NSNibLoading * NSNibLoading_alloc() {
	NSLog(@"NSNibLoading_alloc()");
	return [NSNibLoading alloc];
}
