/* Generated by genstubs.pl
 * (c) 2004 kangaroo, C.J. and Urs
 */

#include <Cocoa/Cocoa.h>

#include <AppKit/NSApplication.h>
#include <AppKit/NSPanel.h>		// For NSCancelButton & NSOKButton.
#include <Foundation/NSObject.h>

NSPageLayout * NSPageLayout$_pageLayout () {
	NSLog(@"NSPageLayout$_pageLayout");
	return [NSPageLayout pageLayout];
}

void NSPageLayout_beginSheetWithPrintInfo_modalForWindow_delegate_didEndSelector_contextInfo (NSPageLayout* THIS, NSPrintInfo * printInfo, NSWindow * docWindow, id delegate, SEL didEndSelector, void * contextInfo) {
	NSLog(@"NSPageLayout_beginSheetWithPrintInfo_modalForWindow_delegate_didEndSelector_contextInfo");
	[THIS beginSheetWithPrintInfo:printInfo modalForWindow:docWindow delegate:delegate didEndSelector:didEndSelector contextInfo:contextInfo];
}

int NSPageLayout_runModal (NSPageLayout* THIS) {
	NSLog(@"NSPageLayout_runModal");
	return [THIS runModal];
}

int NSPageLayout_runModalWithPrintInfo (NSPageLayout* THIS, NSPrintInfo * pInfo) {
	NSLog(@"NSPageLayout_runModalWithPrintInfo");
	return [THIS runModalWithPrintInfo:pInfo];
}

NSView * NSPageLayout_accessoryView (NSPageLayout* THIS) {
	NSLog(@"NSPageLayout_accessoryView");
	return [THIS accessoryView];
}

void NSPageLayout_setAccessoryView (NSPageLayout* THIS, NSView * aView) {
	NSLog(@"NSPageLayout_setAccessoryView");
	[THIS setAccessoryView:aView];
}

NSPrintInfo * NSPageLayout_printInfo (NSPageLayout* THIS) {
	NSLog(@"NSPageLayout_printInfo");
	return [THIS printInfo];
}

void NSPageLayout_readPrintInfo (NSPageLayout* THIS) {
	NSLog(@"NSPageLayout_readPrintInfo");
	[THIS readPrintInfo];
}

void NSPageLayout_writePrintInfo (NSPageLayout* THIS) {
	NSLog(@"NSPageLayout_writePrintInfo");
	[THIS writePrintInfo];
}

void NSPageLayout_convertOldFactor_newFactor (NSPageLayout* THIS, float * oldFactor, float * newFactor) {
	NSLog(@"NSPageLayout_convertOldFactor_newFactor");
	[THIS convertOldFactor:oldFactor newFactor:newFactor];
}

void NSPageLayout_pickedButton (NSPageLayout* THIS, id sender) {
	NSLog(@"NSPageLayout_pickedButton");
	[THIS pickedButton:sender];
}

void NSPageLayout_pickedOrientation (NSPageLayout* THIS, id sender) {
	NSLog(@"NSPageLayout_pickedOrientation");
	[THIS pickedOrientation:sender];
}

void NSPageLayout_pickedPaperSize (NSPageLayout* THIS, id sender) {
	NSLog(@"NSPageLayout_pickedPaperSize");
	[THIS pickedPaperSize:sender];
}

void NSPageLayout_pickedUnits (NSPageLayout* THIS, id sender) {
	NSLog(@"NSPageLayout_pickedUnits");
	[THIS pickedUnits:sender];
}

void NSPageLayout_runPageLayout (NSPageLayout* THIS, id sender) {
	NSLog(@"NSPageLayout_runPageLayout");
	[THIS runPageLayout:sender];
}

NSPageLayout * NSPageLayout$_pageLayout () {
	NSLog(@"NSPageLayout$_pageLayout");
	return [NSPageLayout pageLayout];
}

void NSPageLayout_setAccessoryView (NSPageLayout* THIS, NSView * aView) {
	NSLog(@"NSPageLayout_setAccessoryView");
	[THIS setAccessoryView:aView];
}

NSView * NSPageLayout_accessoryView (NSPageLayout* THIS) {
	NSLog(@"NSPageLayout_accessoryView");
	return [THIS accessoryView];
}

void NSPageLayout_readPrintInfo (NSPageLayout* THIS) {
	NSLog(@"NSPageLayout_readPrintInfo");
	[THIS readPrintInfo];
}

void NSPageLayout_writePrintInfo (NSPageLayout* THIS) {
	NSLog(@"NSPageLayout_writePrintInfo");
	[THIS writePrintInfo];
}

NSPrintInfo * NSPageLayout_printInfo (NSPageLayout* THIS) {
	NSLog(@"NSPageLayout_printInfo");
	return [THIS printInfo];
}

int NSPageLayout_runModalWithPrintInfo (NSPageLayout* THIS, NSPrintInfo * pInfo) {
	NSLog(@"NSPageLayout_runModalWithPrintInfo");
	return [THIS runModalWithPrintInfo:pInfo];
}

int NSPageLayout_runModal (NSPageLayout* THIS) {
	NSLog(@"NSPageLayout_runModal");
	return [THIS runModal];
}

void NSPageLayout_runPageLayout (NSPageLayout* THIS, id sender) {
	NSLog(@"NSPageLayout_runPageLayout");
	[THIS runPageLayout:sender];
}

NSPageLayout * NSPageLayout_alloc(){
	NSLog(@"NSPageLayout_alloc()");
	return [ NSPageLayout alloc ];
}