/* Generated by genstubs.pl
 (c) 2004 kangaroo
*/

#include <Cocoa/Cocoa.h>

#include <Foundation/NSDate.h>

#include <AppKit/NSView.h>

NSSize NSScrollView_frameSizeForContentSize_hasHorizontalScroller_hasVerticalScroller_borderType (NSScrollView* THIS, NSSize cSize, BOOL hFlag, BOOL vFlag, NSBorderType aType) {
	NSLog(@"NSScrollView_frameSizeForContentSize_hasHorizontalScroller_hasVerticalScroller_borderType");
	return [THIS frameSizeForContentSize:cSize hasHorizontalScroller:hFlag hasVerticalScroller:vFlag borderType:aType];
}

NSSize NSScrollView_contentSizeForFrameSize_hasHorizontalScroller_hasVerticalScroller_borderType (NSScrollView* THIS, NSSize fSize, BOOL hFlag, BOOL vFlag, NSBorderType aType) {
	NSLog(@"NSScrollView_contentSizeForFrameSize_hasHorizontalScroller_hasVerticalScroller_borderType");
	return [THIS contentSizeForFrameSize:fSize hasHorizontalScroller:hFlag hasVerticalScroller:vFlag borderType:aType];
}

NSRect NSScrollView_documentVisibleRect (NSScrollView* THIS) {
	NSLog(@"NSScrollView_documentVisibleRect");
	return [THIS documentVisibleRect];
}
NSSize NSScrollView_contentSize (NSScrollView* THIS) {
	NSLog(@"NSScrollView_contentSize");
	return [THIS contentSize];
}
void NSScrollView_setDocumentView (NSScrollView* THIS, NSView * aView) {
	NSLog(@"NSScrollView_setDocumentView");
	[THIS setDocumentView:aView];
}

NSScrollView * NSScrollView_documentView (NSScrollView* THIS) {
	NSLog(@"NSScrollView_documentView");
	return [THIS documentView];
}
void NSScrollView_setContentView (NSScrollView* THIS, NSClipView * contentView) {
	NSLog(@"NSScrollView_setContentView");
	[THIS setContentView:contentView];
}

NSClipView * NSScrollView_contentView (NSScrollView* THIS) {
	NSLog(@"NSScrollView_contentView");
	return [THIS contentView];
}
void NSScrollView_setDocumentCursor (NSScrollView* THIS, NSCursor * anObj) {
	NSLog(@"NSScrollView_setDocumentCursor");
	[THIS setDocumentCursor:anObj];
}

NSCursor * NSScrollView_documentCursor (NSScrollView* THIS) {
	NSLog(@"NSScrollView_documentCursor");
	return [THIS documentCursor];
}
void NSScrollView_setBorderType (NSScrollView* THIS, NSBorderType aType) {
	NSLog(@"NSScrollView_setBorderType");
	[THIS setBorderType:aType];
}

NSBorderType NSScrollView_borderType (NSScrollView* THIS) {
	NSLog(@"NSScrollView_borderType");
	return [THIS borderType];
}
void NSScrollView_setBackgroundColor (NSScrollView* THIS, NSColor * color) {
	NSLog(@"NSScrollView_setBackgroundColor");
	[THIS setBackgroundColor:color];
}

NSColor * NSScrollView_backgroundColor (NSScrollView* THIS) {
	NSLog(@"NSScrollView_backgroundColor");
	return [THIS backgroundColor];
}
void NSScrollView_setDrawsBackground (NSScrollView* THIS, BOOL flag) {
	NSLog(@"NSScrollView_setDrawsBackground");
	[THIS setDrawsBackground:flag];
}

BOOL NSScrollView_drawsBackground (NSScrollView* THIS) {
	NSLog(@"NSScrollView_drawsBackground");
	return [THIS drawsBackground];
}
void NSScrollView_setHasVerticalScroller (NSScrollView* THIS, BOOL flag) {
	NSLog(@"NSScrollView_setHasVerticalScroller");
	[THIS setHasVerticalScroller:flag];
}

BOOL NSScrollView_hasVerticalScroller (NSScrollView* THIS) {
	NSLog(@"NSScrollView_hasVerticalScroller");
	return [THIS hasVerticalScroller];
}
void NSScrollView_setHasHorizontalScroller (NSScrollView* THIS, BOOL flag) {
	NSLog(@"NSScrollView_setHasHorizontalScroller");
	[THIS setHasHorizontalScroller:flag];
}

BOOL NSScrollView_hasHorizontalScroller (NSScrollView* THIS) {
	NSLog(@"NSScrollView_hasHorizontalScroller");
	return [THIS hasHorizontalScroller];
}
void NSScrollView_setVerticalScroller (NSScrollView* THIS, NSScroller * anObject) {
	NSLog(@"NSScrollView_setVerticalScroller");
	[THIS setVerticalScroller:anObject];
}

NSScroller * NSScrollView_verticalScroller (NSScrollView* THIS) {
	NSLog(@"NSScrollView_verticalScroller");
	return [THIS verticalScroller];
}
void NSScrollView_setHorizontalScroller (NSScrollView* THIS, NSScroller * anObject) {
	NSLog(@"NSScrollView_setHorizontalScroller");
	[THIS setHorizontalScroller:anObject];
}

NSScroller * NSScrollView_horizontalScroller (NSScrollView* THIS) {
	NSLog(@"NSScrollView_horizontalScroller");
	return [THIS horizontalScroller];
}
BOOL NSScrollView_autohidesScrollers (NSScrollView* THIS) {
	NSLog(@"NSScrollView_autohidesScrollers");
	return [THIS autohidesScrollers];
}
void NSScrollView_setAutohidesScrollers (NSScrollView* THIS, BOOL flag) {
	NSLog(@"NSScrollView_setAutohidesScrollers");
	[THIS setAutohidesScrollers:flag];
}

void NSScrollView_setHorizontalLineScroll (NSScrollView* THIS, float value) {
	NSLog(@"NSScrollView_setHorizontalLineScroll");
	[THIS setHorizontalLineScroll:value];
}

void NSScrollView_setVerticalLineScroll (NSScrollView* THIS, float value) {
	NSLog(@"NSScrollView_setVerticalLineScroll");
	[THIS setVerticalLineScroll:value];
}

void NSScrollView_setLineScroll (NSScrollView* THIS, float value) {
	NSLog(@"NSScrollView_setLineScroll");
	[THIS setLineScroll:value];
}

float NSScrollView_horizontalLineScroll (NSScrollView* THIS) {
	NSLog(@"NSScrollView_horizontalLineScroll");
	return [THIS horizontalLineScroll];
}
float NSScrollView_verticalLineScroll (NSScrollView* THIS) {
	NSLog(@"NSScrollView_verticalLineScroll");
	return [THIS verticalLineScroll];
}
float NSScrollView_lineScroll (NSScrollView* THIS) {
	NSLog(@"NSScrollView_lineScroll");
	return [THIS lineScroll];
}
void NSScrollView_setHorizontalPageScroll (NSScrollView* THIS, float value) {
	NSLog(@"NSScrollView_setHorizontalPageScroll");
	[THIS setHorizontalPageScroll:value];
}

void NSScrollView_setVerticalPageScroll (NSScrollView* THIS, float value) {
	NSLog(@"NSScrollView_setVerticalPageScroll");
	[THIS setVerticalPageScroll:value];
}

void NSScrollView_setPageScroll (NSScrollView* THIS, float value) {
	NSLog(@"NSScrollView_setPageScroll");
	[THIS setPageScroll:value];
}

float NSScrollView_horizontalPageScroll (NSScrollView* THIS) {
	NSLog(@"NSScrollView_horizontalPageScroll");
	return [THIS horizontalPageScroll];
}
float NSScrollView_verticalPageScroll (NSScrollView* THIS) {
	NSLog(@"NSScrollView_verticalPageScroll");
	return [THIS verticalPageScroll];
}
float NSScrollView_pageScroll (NSScrollView* THIS) {
	NSLog(@"NSScrollView_pageScroll");
	return [THIS pageScroll];
}
void NSScrollView_setScrollsDynamically (NSScrollView* THIS, BOOL flag) {
	NSLog(@"NSScrollView_setScrollsDynamically");
	[THIS setScrollsDynamically:flag];
}

BOOL NSScrollView_scrollsDynamically (NSScrollView* THIS) {
	NSLog(@"NSScrollView_scrollsDynamically");
	return [THIS scrollsDynamically];
}
void NSScrollView_tile (NSScrollView* THIS) {
	NSLog(@"NSScrollView_tile");
	[THIS tile];
}
void NSScrollView_reflectScrolledClipView (NSScrollView* THIS, NSClipView * cView) {
	NSLog(@"NSScrollView_reflectScrolledClipView");
	[THIS reflectScrolledClipView:cView];
}

void NSScrollView_scrollWheel (NSScrollView* THIS, NSEvent * theEvent) {
	NSLog(@"NSScrollView_scrollWheel");
	[THIS scrollWheel:theEvent];
}

void NSScrollView_setRulerViewClass (NSScrollView* THIS, Class rulerViewClass) {
	NSLog(@"NSScrollView_setRulerViewClass");
	[THIS setRulerViewClass:rulerViewClass];
}

Class NSScrollView_rulerViewClass (NSScrollView* THIS) {
	NSLog(@"NSScrollView_rulerViewClass");
	return [THIS rulerViewClass];
}
void NSScrollView_setRulersVisible (NSScrollView* THIS, BOOL flag) {
	NSLog(@"NSScrollView_setRulersVisible");
	[THIS setRulersVisible:flag];
}

BOOL NSScrollView_rulersVisible (NSScrollView* THIS) {
	NSLog(@"NSScrollView_rulersVisible");
	return [THIS rulersVisible];
}
void NSScrollView_setHasHorizontalRuler (NSScrollView* THIS, BOOL flag) {
	NSLog(@"NSScrollView_setHasHorizontalRuler");
	[THIS setHasHorizontalRuler:flag];
}

BOOL NSScrollView_hasHorizontalRuler (NSScrollView* THIS) {
	NSLog(@"NSScrollView_hasHorizontalRuler");
	return [THIS hasHorizontalRuler];
}
void NSScrollView_setHasVerticalRuler (NSScrollView* THIS, BOOL flag) {
	NSLog(@"NSScrollView_setHasVerticalRuler");
	[THIS setHasVerticalRuler:flag];
}

BOOL NSScrollView_hasVerticalRuler (NSScrollView* THIS) {
	NSLog(@"NSScrollView_hasVerticalRuler");
	return [THIS hasVerticalRuler];
}
void NSScrollView_setHorizontalRulerView (NSScrollView* THIS, NSRulerView * ruler) {
	NSLog(@"NSScrollView_setHorizontalRulerView");
	[THIS setHorizontalRulerView:ruler];
}

NSRulerView * NSScrollView_horizontalRulerView (NSScrollView* THIS) {
	NSLog(@"NSScrollView_horizontalRulerView");
	return [THIS horizontalRulerView];
}
void NSScrollView_setVerticalRulerView (NSScrollView* THIS, NSRulerView * ruler) {
	NSLog(@"NSScrollView_setVerticalRulerView");
	[THIS setVerticalRulerView:ruler];
}

NSRulerView * NSScrollView_verticalRulerView (NSScrollView* THIS) {
	NSLog(@"NSScrollView_verticalRulerView");
	return [THIS verticalRulerView];
}
NSScrollView * NSScrollView_alloc() {
	NSLog(@"NSScrollView_alloc()");
	return [NSScrollView alloc];
}
