/* Generated by genstubs.pl
 * (c) 2004 kangaroo, C.J. and Urs
 */

#include <Cocoa/Cocoa.h>


NSSpellServer * NSSpellServer_alloc(){
	NSLog(@"NSSpellServer_alloc()");
	return [ NSSpellServer alloc ];
}