/* Generated by genstubs.pl
 (c) 2004 kangaroo
*/

#include <Cocoa/Cocoa.h>

#include <AppKit/NSActionCell.h>

double NSStepperCell_minValue (NSStepperCell* THIS) {
	NSLog(@"NSStepperCell_minValue");
	return [THIS minValue];
}
void NSStepperCell_setMinValue (NSStepperCell* THIS, double minValue) {
	NSLog(@"NSStepperCell_setMinValue");
	[THIS setMinValue:minValue];
}

double NSStepperCell_maxValue (NSStepperCell* THIS) {
	NSLog(@"NSStepperCell_maxValue");
	return [THIS maxValue];
}
void NSStepperCell_setMaxValue (NSStepperCell* THIS, double maxValue) {
	NSLog(@"NSStepperCell_setMaxValue");
	[THIS setMaxValue:maxValue];
}

double NSStepperCell_increment (NSStepperCell* THIS) {
	NSLog(@"NSStepperCell_increment");
	return [THIS increment];
}
void NSStepperCell_setIncrement (NSStepperCell* THIS, double increment) {
	NSLog(@"NSStepperCell_setIncrement");
	[THIS setIncrement:increment];
}

BOOL NSStepperCell_valueWraps (NSStepperCell* THIS) {
	NSLog(@"NSStepperCell_valueWraps");
	return [THIS valueWraps];
}
void NSStepperCell_setValueWraps (NSStepperCell* THIS, BOOL valueWraps) {
	NSLog(@"NSStepperCell_setValueWraps");
	[THIS setValueWraps:valueWraps];
}

BOOL NSStepperCell_autorepeat (NSStepperCell* THIS) {
	NSLog(@"NSStepperCell_autorepeat");
	return [THIS autorepeat];
}
void NSStepperCell_setAutorepeat (NSStepperCell* THIS, BOOL autorepeat) {
	NSLog(@"NSStepperCell_setAutorepeat");
	[THIS setAutorepeat:autorepeat];
}

NSStepperCell * NSStepperCell_alloc() {
	NSLog(@"NSStepperCell_alloc()");
	return [NSStepperCell alloc];
}
