/* Generated by genstubs.pl
 * (c) 2004 kangaroo, C.J. and Urs
 */

#include <Cocoa/Cocoa.h>

#include <AppKit/NSView.h>

void NSTableHeaderView_setTableView (NSTableHeaderView* THIS, NSTableView * tableView) {
	NSLog(@"NSTableHeaderView_setTableView");
	[THIS setTableView:tableView];
}

NSTableView * NSTableHeaderView_tableView (NSTableHeaderView* THIS) {
	NSLog(@"NSTableHeaderView_tableView");
	return [THIS tableView];
}

int NSTableHeaderView_draggedColumn (NSTableHeaderView* THIS) {
	NSLog(@"NSTableHeaderView_draggedColumn");
	return [THIS draggedColumn];
}

float NSTableHeaderView_draggedDistance (NSTableHeaderView* THIS) {
	NSLog(@"NSTableHeaderView_draggedDistance");
	return [THIS draggedDistance];
}

int NSTableHeaderView_resizedColumn (NSTableHeaderView* THIS) {
	NSLog(@"NSTableHeaderView_resizedColumn");
	return [THIS resizedColumn];
}

NSRect NSTableHeaderView_headerRectOfColumn (NSTableHeaderView* THIS, int column) {
	NSLog(@"NSTableHeaderView_headerRectOfColumn");
	return [THIS headerRectOfColumn:column];
}

int NSTableHeaderView_columnAtPoint (NSTableHeaderView* THIS, NSPoint point) {
	NSLog(@"NSTableHeaderView_columnAtPoint");
	return [THIS columnAtPoint:point];
}

NSTableHeaderView * NSTableHeaderView_alloc(){
	NSLog(@"NSTableHeaderView_alloc()");
	return [ NSTableHeaderView alloc ];
}