/* Generated by genstubs.pl
 (c) 2004 kangaroo
*/

#include <Cocoa/Cocoa.h>

#include <Foundation/NSObject.h>

#include <Foundation/NSGeometry.h>

#include <AppKit/NSView.h>

NSTabViewItem * NSTabViewItem_initWithIdentifier (NSTabViewItem* THIS, NSTabViewItem * identifier) {
	NSLog(@"NSTabViewItem_initWithIdentifier");
	return [THIS initWithIdentifier:identifier];
}

NSTabViewItem * NSTabViewItem_identifier (NSTabViewItem* THIS) {
	NSLog(@"NSTabViewItem_identifier");
	return [THIS identifier];
}
NSTabViewItem * NSTabViewItem_view (NSTabViewItem* THIS) {
	NSLog(@"NSTabViewItem_view");
	return [THIS view];
}
NSTabViewItem * NSTabViewItem_initialFirstResponder (NSTabViewItem* THIS) {
	NSLog(@"NSTabViewItem_initialFirstResponder");
	return [THIS initialFirstResponder];
}
NSString * NSTabViewItem_label (NSTabViewItem* THIS) {
	NSLog(@"NSTabViewItem_label");
	return [THIS label];
}
NSColor * NSTabViewItem_color (NSTabViewItem* THIS) {
	NSLog(@"NSTabViewItem_color");
	return [THIS color];
}
NSTabState NSTabViewItem_tabState (NSTabViewItem* THIS) {
	NSLog(@"NSTabViewItem_tabState");
	return [THIS tabState];
}
NSTabView * NSTabViewItem_tabView (NSTabViewItem* THIS) {
	NSLog(@"NSTabViewItem_tabView");
	return [THIS tabView];
}
void NSTabViewItem_setIdentifier (NSTabViewItem* THIS, NSTabViewItem * identifier) {
	NSLog(@"NSTabViewItem_setIdentifier");
	[THIS setIdentifier:identifier];
}

void NSTabViewItem_setLabel (NSTabViewItem* THIS, NSString * label) {
	NSLog(@"NSTabViewItem_setLabel");
	[THIS setLabel:label];
}

void NSTabViewItem_setColor (NSTabViewItem* THIS, NSColor * color) {
	NSLog(@"NSTabViewItem_setColor");
	[THIS setColor:color];
}

void NSTabViewItem_setView (NSTabViewItem* THIS, NSView * view) {
	NSLog(@"NSTabViewItem_setView");
	[THIS setView:view];
}

void NSTabViewItem_setInitialFirstResponder (NSTabViewItem* THIS, NSView * view) {
	NSLog(@"NSTabViewItem_setInitialFirstResponder");
	[THIS setInitialFirstResponder:view];
}

void NSTabViewItem_drawLabel_inRect (NSTabViewItem* THIS, BOOL shouldTruncateLabel, NSRect labelRect) {
	NSLog(@"NSTabViewItem_drawLabel_inRect");
	[THIS drawLabel:shouldTruncateLabel inRect:labelRect];
}

NSSize NSTabViewItem_sizeOfLabel (NSTabViewItem* THIS, BOOL computeMin) {
	NSLog(@"NSTabViewItem_sizeOfLabel");
	return [THIS sizeOfLabel:computeMin];
}

NSTabViewItem * NSTabViewItem_alloc() {
	NSLog(@"NSTabViewItem_alloc()");
	return [NSTabViewItem alloc];
}
