/* Generated by genstubs.pl
 * (c) 2004 kangaroo, C.J. and Urs
 */

#include <Cocoa/Cocoa.h>

#include <AppKit/NSTextStorage.h>

NSArray * NSTextStorageScripting_attributeRuns (NSTextStorageScripting* THIS) {
	NSLog(@"NSTextStorageScripting_attributeRuns");
	return [THIS attributeRuns];
}

void NSTextStorageScripting_setAttributeRuns (NSTextStorageScripting* THIS, NSArray * attributeRuns) {
	NSLog(@"NSTextStorageScripting_setAttributeRuns");
	[THIS setAttributeRuns:attributeRuns];
}

NSArray * NSTextStorageScripting_paragraphs (NSTextStorageScripting* THIS) {
	NSLog(@"NSTextStorageScripting_paragraphs");
	return [THIS paragraphs];
}

void NSTextStorageScripting_setParagraphs (NSTextStorageScripting* THIS, NSArray * paragraphs) {
	NSLog(@"NSTextStorageScripting_setParagraphs");
	[THIS setParagraphs:paragraphs];
}

NSArray * NSTextStorageScripting_words (NSTextStorageScripting* THIS) {
	NSLog(@"NSTextStorageScripting_words");
	return [THIS words];
}

void NSTextStorageScripting_setWords (NSTextStorageScripting* THIS, NSArray * words) {
	NSLog(@"NSTextStorageScripting_setWords");
	[THIS setWords:words];
}

NSArray * NSTextStorageScripting_characters (NSTextStorageScripting* THIS) {
	NSLog(@"NSTextStorageScripting_characters");
	return [THIS characters];
}

void NSTextStorageScripting_setCharacters (NSTextStorageScripting* THIS, NSArray * characters) {
	NSLog(@"NSTextStorageScripting_setCharacters");
	[THIS setCharacters:characters];
}

NSFont * NSTextStorageScripting_font (NSTextStorageScripting* THIS) {
	NSLog(@"NSTextStorageScripting_font");
	return [THIS font];
}

void NSTextStorageScripting_setFont (NSTextStorageScripting* THIS, NSFont * font) {
	NSLog(@"NSTextStorageScripting_setFont");
	[THIS setFont:font];
}

NSColor * NSTextStorageScripting_foregroundColor (NSTextStorageScripting* THIS) {
	NSLog(@"NSTextStorageScripting_foregroundColor");
	return [THIS foregroundColor];
}

void NSTextStorageScripting_setForegroundColor (NSTextStorageScripting* THIS, NSColor * color) {
	NSLog(@"NSTextStorageScripting_setForegroundColor");
	[THIS setForegroundColor:color];
}

NSTextStorageScripting * NSTextStorageScripting_alloc(){
	NSLog(@"NSTextStorageScripting_alloc()");
	return [ NSTextStorageScripting alloc ];
}