/* Generated by genstubs.pl
 (c) 2004 kangaroo
*/

#include <Cocoa/Cocoa.h>

#include <Foundation/Foundation.h>

#include <AppKit/NSUserInterfaceValidation.h>

#include <AppKit/NSText.h>

#include <AppKit/NSToolbar.h>

NSToolbarItem * NSToolbarItem_initWithItemIdentifier (NSToolbarItem* THIS, NSString * itemIdentifier) {
	NSLog(@"NSToolbarItem_initWithItemIdentifier");
	return [THIS initWithItemIdentifier:itemIdentifier];
}

NSString * NSToolbarItem_itemIdentifier (NSToolbarItem* THIS) {
	NSLog(@"NSToolbarItem_itemIdentifier");
	return [THIS itemIdentifier];
}
NSToolbar * NSToolbarItem_toolbar (NSToolbarItem* THIS) {
	NSLog(@"NSToolbarItem_toolbar");
	return [THIS toolbar];
}
void NSToolbarItem_setLabel (NSToolbarItem* THIS, NSString * label) {
	NSLog(@"NSToolbarItem_setLabel");
	[THIS setLabel:label];
}

NSString * NSToolbarItem_label (NSToolbarItem* THIS) {
	NSLog(@"NSToolbarItem_label");
	return [THIS label];
}
void NSToolbarItem_setPaletteLabel (NSToolbarItem* THIS, NSString * paletteLabel) {
	NSLog(@"NSToolbarItem_setPaletteLabel");
	[THIS setPaletteLabel:paletteLabel];
}

NSString * NSToolbarItem_paletteLabel (NSToolbarItem* THIS) {
	NSLog(@"NSToolbarItem_paletteLabel");
	return [THIS paletteLabel];
}
void NSToolbarItem_setToolTip (NSToolbarItem* THIS, NSString* toolTip) {
	NSLog(@"NSToolbarItem_setToolTip");
	[THIS setToolTip:toolTip];
}

NSString * NSToolbarItem_toolTip (NSToolbarItem* THIS) {
	NSLog(@"NSToolbarItem_toolTip");
	return [THIS toolTip];
}
void NSToolbarItem_setMenuFormRepresentation (NSToolbarItem* THIS, NSMenuItem * menuItem) {
	NSLog(@"NSToolbarItem_setMenuFormRepresentation");
	[THIS setMenuFormRepresentation:menuItem];
}

NSMenuItem * NSToolbarItem_menuFormRepresentation (NSToolbarItem* THIS) {
	NSLog(@"NSToolbarItem_menuFormRepresentation");
	return [THIS menuFormRepresentation];
}
void NSToolbarItem_setTag (NSToolbarItem* THIS, int tag) {
	NSLog(@"NSToolbarItem_setTag");
	[THIS setTag:tag];
}

int NSToolbarItem_tag (NSToolbarItem* THIS) {
	NSLog(@"NSToolbarItem_tag");
	return [THIS tag];
}
void NSToolbarItem_setTarget (NSToolbarItem* THIS, NSToolbarItem * target) {
	NSLog(@"NSToolbarItem_setTarget");
	[THIS setTarget:target];
}

NSToolbarItem * NSToolbarItem_target (NSToolbarItem* THIS) {
	NSLog(@"NSToolbarItem_target");
	return [THIS target];
}
void NSToolbarItem_setAction (NSToolbarItem* THIS, SEL action) {
	NSLog(@"NSToolbarItem_setAction");
	[THIS setAction:action];
}

SEL NSToolbarItem_action (NSToolbarItem* THIS) {
	NSLog(@"NSToolbarItem_action");
	return [THIS action];
}
void NSToolbarItem_setEnabled (NSToolbarItem* THIS, BOOL enabled) {
	NSLog(@"NSToolbarItem_setEnabled");
	[THIS setEnabled:enabled];
}

BOOL NSToolbarItem_isEnabled (NSToolbarItem* THIS) {
	NSLog(@"NSToolbarItem_isEnabled");
	return [THIS isEnabled];
}
void NSToolbarItem_setImage (NSToolbarItem* THIS, NSImage* image) {
	NSLog(@"NSToolbarItem_setImage");
	[THIS setImage:image];
}

NSImage * NSToolbarItem_image (NSToolbarItem* THIS) {
	NSLog(@"NSToolbarItem_image");
	return [THIS image];
}
void NSToolbarItem_setView (NSToolbarItem* THIS, NSView * view) {
	NSLog(@"NSToolbarItem_setView");
	[THIS setView:view];
}

NSView * NSToolbarItem_view (NSToolbarItem* THIS) {
	NSLog(@"NSToolbarItem_view");
	return [THIS view];
}
void NSToolbarItem_setMinSize (NSToolbarItem* THIS, NSSize size) {
	NSLog(@"NSToolbarItem_setMinSize");
	[THIS setMinSize:size];
}

NSSize NSToolbarItem_minSize (NSToolbarItem* THIS) {
	NSLog(@"NSToolbarItem_minSize");
	return [THIS minSize];
}
void NSToolbarItem_setMaxSize (NSToolbarItem* THIS, NSSize size) {
	NSLog(@"NSToolbarItem_setMaxSize");
	[THIS setMaxSize:size];
}

NSSize NSToolbarItem_maxSize (NSToolbarItem* THIS) {
	NSLog(@"NSToolbarItem_maxSize");
	return [THIS maxSize];
}
void NSToolbarItem_validate (NSToolbarItem* THIS) {
	NSLog(@"NSToolbarItem_validate");
	[THIS validate];
}
BOOL NSToolbarItem_allowsDuplicatesInToolbar (NSToolbarItem* THIS) {
	NSLog(@"NSToolbarItem_allowsDuplicatesInToolbar");
	return [THIS allowsDuplicatesInToolbar];
}
BOOL NSToolbarItem_validateToolbarItem (NSToolbarItem* THIS, NSToolbarItem * theItem) {
	NSLog(@"NSToolbarItem_validateToolbarItem");
	return [THIS validateToolbarItem:theItem];
}

NSToolbarItem * NSToolbarItem_alloc() {
	NSLog(@"NSToolbarItem_alloc()");
	return [NSToolbarItem alloc];
}
